### ISSUE TITLE
Request user location

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/Catch-em-all#10]
One requirement is to request the user's location from the client device (mobile phone/tablet or desktop browser?) and display it on the map. I suggest that we talk to members of the PokeMap team as they might already request the location as part of their project.

**Comment by sacdallago** [comment]
It's a very easy task to do in JS ;)

**Comment by johartl** [comment]
That's what I like to hear :)

**Comment by MajorBreakfast** [comment]
We can use `navigator.geolocation.getCurrentPosition(success, error)`

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation

**Comment by sacdallago** [comment]
@MajorBreakfast precisely.
Make sure you check the browser compatibility before that. I would say that if someone with a shitty browser is trying to access then just tell them to upgrade! It's 2016, no need to be so retro-friendly!

As a general note: @PokemonGoers/catch-em-all start assigning labels, milestones and assignees to issues. Maybe you can discuss and do this during your meeting.  It's important for you and for us :)

**Comment by MajorBreakfast** [comment]
Supported by every major browser http://caniuse.com/#search=geolocation
