### ISSUE TITLE
Adjustments to the about page

### ISSUE THREAD

**Issue by AlexanderLill** [PokemonGoers/Catch-em-all#100]
Feedback from @goldbergtatyana ( Taken from #95 )

> I like the About page, too! A lot!
> 
> Comments:
> - "augmented reality title PokemonGo" reads strange to me. Maybe instead "augmented reality game entitled PokemonGo". If you wrote the way you meant and in your opinion it is correct, then please ignore the comment.
> - Please put "Pokemon Legends" at the bottom of your list. The section can also be centralized, if you think it will make it look better.
> - Also, please have Burkhard listed first, Lothar second and Tim third.
> - The Sponsors sentence I would change to "We want to thank Iteratec for sponsoring our project and for giving interesting insights into the company."
> 
> Most likely this is still not the last round of a review, yet very looking forward to the result 😄

**Comment by AlexanderLill** [comment]
Issue Nr
![100](https://badges.mozilla.org/media/uploads/badge/a/c/acd0cd3ead8b5bbd2faaf335467a98b8_image_1363634027_0161.png)

\o/ :P

**Comment by AlexanderLill** [comment]
Now is also the time to tell us if you want any URL behind your particular name. Otherwise we could just put a github link for every profile.

If you want your customized website link, reply here ;)

@PokemonGoers/catch-em-all 
@PokemonGoers/hashpokemongo 
@PokemonGoers/pokedata 
@PokemonGoers/pokemap-1 
@PokemonGoers/pokemap-2

**Comment by sacdallago** [comment]
Even better, propose changes on the relative PR? @AlexanderLill

**Comment by gyachdav** [comment]
https://www.linkedin.com/in/gyachdav

**Comment by sacdallago** [comment]
@gyachdav I did that already 💃

**Comment by AlexanderLill** [comment]
- Alexander Lill: https://www.github.com/AlexanderLill

**Comment by sacdallago** [comment]
@AlexanderLill please focus on more urgent matters

**Comment by sacdallago** [comment]
Ok. I believe this can be closed. If anything comes up, we will reopen or reference
