### ISSUE TITLE
Map filtering

### ISSUE THREAD

**Issue by WoH** [PokemonGoers/Catch-em-all#101]
Since the filter is now well-synced throughout the app, we need to pass it to the pokemap.
This requires transforming the Filter() to a filterObj{} according to the specification (https://github.com/PokemonGoers/Catch-em-all/issues/24).

> - `filter({ pokemonIds, sightingsSince, predictionsUntil })` applies filter options to the map.
>   - `pokemonIds` Array of Pokemon IDs which are shown (applies to predictions and sightings) on the map. If `null` show all 151 Pokemon.
>   - `sightingsSince` Time in seconds for which sightings (includes mobs) in the past are shown. If `0` don't show any sightings.
>   - `predictionsUntil` Time in seconds for which predictions are shown. If `0` don't show any predictions.

Predictions and Sightings should be passed as Date().
Ideally, the lookup / conversion should be done in a Service.

@PokemonGoers/catch-em-all

**Comment by johartl** [comment]
I'm working on this.

**Comment by WoH** [comment]
Are you sure? I was hoping someone else would want to get some lines down tbh and I thought this would be a perfect opportunity. But since we are running out of time I guess it's fine.

Edit: Maybe give anyone else a chance until tomorrow morning?
