### ISSUE TITLE
List of available/predicted Pokemon

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/Catch-em-all#11]
From the project description:

> Then, there needs to be a menu bar or something available (e.g. above the map or on the right side to it) that will list currently active or predicted pokemons. Clicking on one of them will make other pokemons on the map disappear, except of this clicked one.

Again, we need to collaborate with the PokeMap team and discuss how we can handle the interaction between the Pokemon list and the map.
For the design and location of the list within the app please refer to #5.

**Comment by AlexanderLill** [comment]
@johartl I am not entirely sure what this issue was about. It also is quite old :)

Can you elaborate, or should we just close it?

**Comment by johartl** [comment]
I think we already have that functionality included in the filter popover. So yes you're right, we can close this issue.
