### ISSUE TITLE
[SCSS] PokeDetail Page

### ISSUE THREAD

**Issue by WoH** [PokemonGoers/Catch-em-all#114]
The evolutions component is too wide and the attack type labels are off.

![screenshot_20161011-213953](https://cloud.githubusercontent.com/assets/2697771/19286322/82b1e142-8ffd-11e6-831b-b2d63b4e6a64.png)

**Comment by johartl** [comment]
I have another thing to add. The animated Pokemon gifs are nice but since their resolution is too low with respect to this size and resolution I would also replace them with the high-res SVGs.

**Comment by WoH** [comment]
Agree

**Comment by philbu** [comment]
Fixing these issues in PR #115
