### ISSUE TITLE
Map bugs

### ISSUE THREAD

**Issue by MajorBreakfast** [PokemonGoers/Catch-em-all#117]
I am opening this as a meta issue for now. Maybe they're bugs due to the integration, maybe they're legit map bugs.

**404 Bug**
![map-bug](https://cloud.githubusercontent.com/assets/340142/19347327/8a6be030-9148-11e6-84ea-62e0fce10d06.jpg)
When panning and zooming around the map **via touch** I get 404s for the images. (Tested in Chrome on Windows)

**Pokemon Visibility Bug**
When I zoom in and out I see Pokemon appearing and disappearing. Especially when I zoom in, I expect all visible Pokemon to stay visible. That's not the case, though. Some just disappear for no reason.

**Comment by sacdallago** [comment]
You are using the map from @PokemonGoers/pokemap-1 , right? Makes sense to open the issue there?

**Comment by sacdallago** [comment]
Updates?

**Comment by WoH** [comment]
PokeMap-1 apparently solved that by downgrading leaflet.
