### ISSUE TITLE
Iteratec logo 

### ISSUE THREAD

**Issue by gyachdav** [PokemonGoers/Catch-em-all#118]
Iteratec requested:
- [ ] Place logo (just the face) more prominently somewhere in the APP/Webpage? (@gyachdav: I suggest to put in the right side of the footer)
- [ ] have the logo on the map where Iteratec's offices are situated?

![image](https://cloud.githubusercontent.com/assets/4074881/19347560/12ff95b4-9152-11e6-8770-4976237ae5f7.png)
![image](https://cloud.githubusercontent.com/assets/4074881/19347563/1728179c-9152-11e6-89e3-c10451c15dee.png)

**Comment by MajorBreakfast** [comment]
I make myself responsible. Alex is busy with exams.

**Comment by MajorBreakfast** [comment]
- I suggest adding the text "Sponsored by" to clarify why their logo is placed
- We should use the full version of the logo to distinguish it from the commonly known Mac logo

![macos-logo svg](https://cloud.githubusercontent.com/assets/340142/19348650/36482444-914f-11e6-951d-384c56122325.png)

I suggest placing it in the sidebar. That way it is very visible:

![logo-placement](https://cloud.githubusercontent.com/assets/340142/19348803/006202fe-9150-11e6-9556-96a766cc7d9e.png)

Would that be alright?

**Comment by gyachdav** [comment]
> We should use the full version of the logo to distinguish it from the commonly known Mac logo

They asked us for just the face so let's just do what they asked

**Comment by MajorBreakfast** [comment]
@gyachdav Okay then just the face.

**Comment by sacdallago** [comment]
@MajorBreakfast for the logo on the map, this is an issue for the map teams @PokemonGoers/pokemap-1 @PokemonGoers/pokemap-2

**Comment by MajorBreakfast** [comment]
PR merged
