### ISSUE TITLE
Remove license text from sidebar

### ISSUE THREAD

**Issue by MajorBreakfast** [PokemonGoers/Catch-em-all#119]
Currently the text in the sidebar says "Licensed under Creative Commons Attribution 3.0". I suggest removing it, here's why:
- Imprecise/Wrong: Various parts of the application have different licenses attached, e.g. Angular 2 is under the MIT license. To state that the whole application is CC is not correct.
- Clutter: There is no need to place a license statement directly in the sidebar.

![license](https://cloud.githubusercontent.com/assets/340142/19349085/87a267f8-9151-11e6-808a-7fd8d4b11a7f.jpg)

**Comment by MajorBreakfast** [comment]
I'd like to have some thoughts on this. I'll do the change in a PR in conjunction with #118

**Comment by sacdallago** [comment]
@MajorBreakfast remove it. If the licenses are in conflict, we must figure out which on is the least inclusive and use that one, in case.

_Edit_: thanks for noticing

**Comment by MajorBreakfast** [comment]
Will do. Let's keep the issue open until it's done.

**Comment by MajorBreakfast** [comment]
Implemented in #123
