### ISSUE TITLE
Pokedex / Detail Pokemon page

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/Catch-em-all#12]
From the project description:

> This website should contain sections about each Pokemon and its details.
> [...]
> Separate web pages would allow the search and presentation of individual Pokemons and the information we gathered about them, including third party data (project A) and twitter analysis (project C).

**Comment by johartl** [comment]
@AlexanderLill Are you working on this? Any updates?

**Comment by AlexanderLill** [comment]
@johartl I am, I opened a branch and started working on it, need to figure out how the pokedex page should look like though. Currently I have a list of pokemon to choose from, and then I will show a page for the selected pokemon. I am also still waiting for the @PokemonGoers/pokedata team if and which additional info they will provide for the pokemon, except the data already available on their API :)

**Comment by jonas-he** [comment]
@AlexanderLill Sorry but i somehow didnt notice your post over at #23 .
Honestly I think that our data covers the majority of aspects (Number, Name, Classification, Types, Reistant, Weaknesses, Attacks, Weight, Height, FleeRate, Next/Prev Evoultion, MaxCP/HP, gender), but if you have suggestions you can open up an issue in our repo and we can discuss.

**Comment by AlexanderLill** [comment]
![img_20160913_234849](https://cloud.githubusercontent.com/assets/11082297/18495291/120c9446-7a1d-11e6-8a81-e1710b8e8c0d.jpg)
- [x] Implement PokeType (Pokemon attributes)
- [x] Implement PokeStats (Top area incl. description)
- [x] Implement Evolution (Evolution of pokemon)
- [x] Implement Attack (Attacks of pokemon)

**Comment by AlexanderLill** [comment]
See #66 for the pull request that includes pokemon description, evolution and attack for now.
The description is already available in the API, although @PokemonGoers/pokedata did not merge the pull request yet :) Thanks @jonas-he @fabe85

**Comment by MajorBreakfast** [comment]
We've merged it into the develop branch.
