### ISSUE TITLE
pokedex glyphs and tootips

### ISSUE THREAD

**Issue by gyachdav** [PokemonGoers/Catch-em-all#120]
Can anyone tell me what the glyphs (e.g. heart, paw, medal, person(??)) mean. Are these suppose to be some universally recognized symbols in the pokemongo universe? 

if not some legend or tool tips would be useful here

**Comment by MajorBreakfast** [comment]
Yep, I agree. It's very cryptic. I've created #121 for a redesign of the whole page. The design of the page has been bothering me for quite a while now.

The new design will use text in favor of icons. Then it'll be much clearer. Anyway, the glyphs mean "Max Health Points", "Max Combat Points ", "Flee Rate", "Weight" and "Height"

**Comment by gyachdav** [comment]
okay so this one can be closed?

**Comment by MajorBreakfast** [comment]
@gyachdav I agree
