### ISSUE TITLE
Improve PokeDex Detail Page Design

### ISSUE THREAD

**Issue by MajorBreakfast** [PokemonGoers/Catch-em-all#121]
I'm working on making the PokeDex more modern
- Less formal, more fibrant design
- Responsive
- Improve clarity: E.g. Make Pokemon stats less cryptic #120

**Comment by MajorBreakfast** [comment]
PR will come tomorrow. But, here's a sneak preview:

![new-pokedex](https://cloud.githubusercontent.com/assets/340142/19358210/5efb389c-9175-11e6-85ac-36c267de200c.jpg)

I consider the stuff shown on the screenshot finished. However, I still have to revamp the attacks section (not visible above).

Side note: The stuff you see is super responsive. The header section can split on small devices and the evolutions now adapt to the screen size better than before. Also, I've simplified the markup (html) under the hood considerably.

**Comment by philbu** [comment]
I don't really like the cloudy design of the stats.

**Comment by WoH** [comment]
What's the reason for the rather obtrusive background color? I can see this looking a lot better as a navbar color.

E: As already noticeable in your screenshot, this will be very uneasy on the eyes, considering all the different colors of the badges it will be displayed with.

**Comment by sacdallago** [comment]
@MajorBreakfast I appreciate the effort.

_Things I like_
I like the re-arrangement of stuff, it looks cleaner and more compact. I also like the bigger image in the header.

_Things I don't like_
The background is too obtrusive, and I don't fully understand the reason for the clouds to be :) Boxes can do as well, right?

I believe if you account for the BG and the clouds, the PR might be good to go

**Comment by MajorBreakfast** [comment]
Thanks for your feedback.
The major difference is that the new design is responsive because it adjusts according to the screen size. I'll provide the PR later, after we merge everybody is welcome to propose nice colors and shapes. Let's focus on the broad design aspects for now. I'm confident that we can come up with something that everybody likes together.

![pokedex-details-big](https://cloud.githubusercontent.com/assets/340142/19379717/b159bdce-91f3-11e6-8a3c-b0dfa806ac77.PNG)

**Comment by MajorBreakfast** [comment]
Merged.

(We'll get rid of the clouds as soon as I come up with something suitable to replace them. Hehe :)
