### ISSUE TITLE
Curtain call

### ISSUE THREAD

**Issue by sacdallago** [PokemonGoers/Catch-em-all#138]
Dear @PokemonGoers/catch-em-all -ers, it's time to meet the feature freeze!

I would like to set the feature freeze to coming **Monday, 24th Oct, @ 23:59**. What this means is: by Monday evening you should finalize the implementation of the open features and get rid of those you think are too immature to make it to production. This also means that after Monday you will still have time to fix eventual bugs, clean up code and make **slight** design changes.

I would like to get feedback from possibly all of you, opinions and concerns regarding this matter. Also: it would be nice to get a list of features which will **not** make it to production.

Lastly: after feature freeze, you will have one week to clean code. After that it's officially over (though practically, if you want, you can go on working on this as much as you like! It's after all open source, the automatic deployment is bound to this repo, etc. So: it's up to each and everyone of you).

**Comment by WoH** [comment]
Looking good so far:
https://github.com/PokemonGoers/Catch-em-all/projects

**Comment by sacdallago** [comment]
@WoH at least someone has some sense of music around here!

**Comment by MajorBreakfast** [comment]
Yo, slim shady xD

We're currently working on:
- Filter UI: Currently has data binding bugs, my three state checkbox issue open and then we need to fix the selection behavior. Assuming that the map team has implemented filtering correctly this should be doable.
- Notifications: @johartl picked it up and worked on it
- Pokemon Tweets: @mfkaptan is working on it. I've just bumped the issue #68 
- Predictions UI: The card itself was implemented by @WoH, but I've never seen a prediction on the map. That is what troubles me...

**Comment by sacdallago** [comment]
![](http://static.tumblr.com/ifpspe0/zL1m78md7/eminemapproves.jpg)

I'll try to figure out the websocket issue ( @johartl knows what I'm talking about). Reverse proxy + firewall should do, but I'm traveling to SFO so expect slight delays. @gyachdav and @goldbergtatyana will ping the s**\* out of me if anything urgent comes up :)
