### ISSUE TITLE
Everyone should join our gitter room

### ISSUE THREAD

**Issue by MajorBreakfast** [PokemonGoers/Catch-em-all#14]
Hey everyone, 

**Edit: Changed What's App to Gitter.**

Everyone should install the App on his/her **cell phone** and join our room.

Note: Plz use the  ~~What's App~~ Gitter group for small inquiries only. Let's keep the main communication on github! And: You know how it is, don't spam. That only leads to people muting the channel. Only post stuff that's relevant to everyone. No, one-on-one chats ;)

**Comment by MajorBreakfast** [comment]
@philbu, @Georrgi, @johartl, @mfkaptan, @Lugitan Plz join the gitter room and install the gitter app.

**Comment by WoH** [comment]
Our gitter for everything around the Project:
https://gitter.im/rostlabjs16projecte/Lobby

I'd suggest to leave this open though since I agree they should join the other one aswell.

**Comment by WoH** [comment]
@MajorBreakfast I added you, hope you don't mind

**Comment by MajorBreakfast** [comment]
@WoH Perfect.

I also added everyone to the public gitter room.

Everyone is now in both rooms. So, I'm closing this issue now.
