### ISSUE TITLE
Request timeout for /socket.io/socket.io.js

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/Catch-em-all#144]
@sacdallago Something with the nginx configuration does not seem to be right. The request for https://predictemall.online/socket.io/socket.io.js times out eventually. Maybe it has something to do with #139 ?

**Comment by johartl** [comment]
Seems to be magically fixed now. I hope it stays like this :)

**Comment by sacdallago** [comment]
if it fixed itself, it shouldn't have had. I haven't yet exported the port for the websocket :D Are you sure everything works there? It would be.. very, VERY strange
