### ISSUE TITLE
Fix Filter UI Data Binding

### ISSUE THREAD

**Issue by MajorBreakfast** [PokemonGoers/Catch-em-all#151]
When switching between the two tabs the sliders don't keep their value properly.

**Comment by WoH** [comment]
Can you elaborate please? Does this happen on develop? I checked the hosted app https://predictemall.online/index.html and not only did it get my previous settings from localstorage, but switching between tabs didn't seem to be an issue. Both slider and selection values.

**Comment by MajorBreakfast** [comment]
It was on https://predictemall.online and just minutes ago. But I can't reproduce it for the world now. Maybe I mistook the effects of #152 and that's why the slider jumped. I'll reopen with a video should I be able to reproduce it.
