### ISSUE TITLE
MapPage ionViewDidEnter error: _.debounce is not a function

### ISSUE THREAD

**Issue by MajorBreakfast** [PokemonGoers/Catch-em-all#153]
When I develop locally I get the following now:

![debounce](https://cloud.githubusercontent.com/assets/340142/19657348/25246898-9a24-11e6-90d3-a7d546f63b71.png)

I just ran `npm install -g ionic`, deleted the `node_modules/` folder and reinstalled everything.

**Comment by MajorBreakfast** [comment]
Ah, I should note the because of this the map now doesn't show.

**Comment by sacdallago** [comment]
That seems like a discriminative feature, yes. For me that error doesn't occur, though.

**Comment by MajorBreakfast** [comment]
I've just now deleted my local repository entirely and reinstalled everything. This still persists.

**Comment by WoH** [comment]
https://github.com/PokemonGoers/PokeMap-1/blob/develop/module/main.js#L155
^ My tip.

We are calling initializeMap in MapPage's ionViewDidEnter. Weird coincidence that the Map doesn't show if something fails in there ;)

Would be nice if you could open up an issue @PokemonGoers/pokemap-1 and ask them to look into it.
