### ISSUE TITLE
Maintenance notice

### ISSUE THREAD

**Issue by sacdallago** [PokemonGoers/Catch-em-all#161]
Between the 8th and 11th Nov, the infrastructure where I'm hosting svc is gonna go down for maintenance.

If by then I can migrate also the development images to the other cloud account / machine, I'll let you know, but expect two days of down.

This is actually a good imposed condition to start using predictemall.online for all testing purposes.

**Comment by sacdallago** [comment]
Holds valid for @PokemonGoers/catch-em-all too!

**Comment by sacdallago** [comment]
This holds now till nov 21st. But is irrelevant for this project

**Comment by WoH** [comment]
How about releasing on 22nd so I get a nice b-day present on top :dancing_women: :champagne:

**Comment by sacdallago** [comment]
It would have been cool if they finished yesterday too, on my birthday :princess:

**Comment by WoH** [comment]
Belated Happy Birthday!
Have you already agreed on a person to blame in the disclaimer?

**Comment by gyachdav** [comment]
Please put for now that Nom Ekop is the responsible person. Thanks
