### ISSUE TITLE
Use feature model

### ISSUE THREAD

**Issue by sacdallago** [PokemonGoers/Catch-em-all#2]
Please --->**DON'T**<--- commit on develop directly.
Open a branch for your feature, work on it, open a PR when done, get it approved or rejected by other developers in your team.

We have highlighted multiple times the correct way of submitting code until now, please read it and/or watch the video, people not following the correct pattern will be deducted points from now on.

**Comment by sacdallago** [comment]
@philbu

**Comment by philbu** [comment]
I'm sorry. Saw that email after my push. Won't happen again.

**Comment by sacdallago** [comment]
All cool ;)
