### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by MajorBreakfast** [PokemonGoers/Catch-em-all#20]
- [ ] Domain (see #62)
- [x] SSL certificate: StartSSL
- [x] Hosting provider that supports SSL: Docker node provided by chair
- [x] CDN (optional, but recommended): Maybe cloudflare, but let's not use a CDN during development
- [x] ~~MongoDB service (Project A probably won't do that for us)~~

---
- ~~Which provider should we use?~~
- ~~Who wants to look into what?~~
- ~~Maybe something with docker?~~

---

~~Possible hosting provider:~~
~~**Heroku** has a free tier with SSL support [Announcement on Heroku Blog](https://blog.heroku.com/announcing_heroku_free_ssl_beta_and_flexible_dyno_hours)~~

---

Domain name summary:
- `pokemap24.com`
- `pokesnag.com`

Notes:
- Please check the availability before you suggest a name
- @sacdallago mentioned that the name should not contain TUM

**Comment by sacdallago** [comment]
1. We have a server
2. We are using docker already for the API project (although only one node, I'm poor :D ) --> would be nice to keep the docker story up
3. Let's encrypt for the SSL cert or startSSL as free alternatives
4. I'd rather stay away from heroku because while with docker cloud you can find a workaround to resolve the app to your own DNS for free, not so sure about heroku
5. Why would you need MongoDB? :)

I think it might be worth mentioning: your project should be mostly a front-end project! You should get the data via http calls to the API server :) Or, actually: users connecting to the app will instantiate the calls to the API.
Take a look at last semester's web-app, it basically just instructs the user's browser to get the data from the API at various levels.

**Comment by MajorBreakfast** [comment]
@sacdallago Ah okay. I didn't know where the separation was going to be. So, we don't need a database.

Let's use the docker node by the chair. I've updated the list.

**Comment by MajorBreakfast** [comment]
@sacdallago Will the chair provide us with the domain as well?

**Comment by sacdallago** [comment]
@MajorBreakfast We didn't buy a domain just yet. If you have any proposals (of available ones, of course) I'd be happy to hear them.
Preferably we all vote (all as in all 35 people involved in this project).

Unfortunately we have to buy everything ourselves. From the chair we only get one server, which happens to be very limited and not too collaborative at times. So I'm usually falling back on my own stuff (even the docker node is my own node, right now).

@gyachdav was nice enough to sponsor the domain last sem.. We'll have to see how we can make this happen this semester.

**Comment by MajorBreakfast** [comment]
pokeTUM.com :)

pokemon.rostlab.org

**Comment by sacdallago** [comment]
Oh... if possible, leave TUM out of the game :D They don't like us affiliating them too much 😂

**Comment by MajorBreakfast** [comment]
pokemap24.com

**Comment by gyachdav** [comment]
PokePoint is my preferred name

**Comment by MajorBreakfast** [comment]
pokepoint.com is taken

**Comment by MajorBreakfast** [comment]
pokesnag.com

**Comment by gyachdav** [comment]
doesn't have to be a .com. Also this can be the app name and not the website. But anyways we can collect name suggestions and bring them to a general vote during presentation week. @MajorBreakfast can you start a doodle around that?

**Comment by goldbergtatyana** [comment]
Poke.map, poke.go, poke.point (if any of these possible)

**Comment by mfkaptan** [comment]
Have you guys heard about https://education.github.com/pack ? Could be useful for domain, ssl and hosting (even if not, still useful for personal usage ;) )

**Comment by gyachdav** [comment]
- [ ] @MajorBreakfast  - Create doodle open to all students and mentors to vote for suggested app/website name
- [ ] @johartl - Deploy a live demo

**Comment by MajorBreakfast** [comment]
@gyachdav Doodle is no problem, but I think we need more suggestions!

@PokemonGoers/PokeData
@PokemonGoers/pokemap-1
@PokemonGoers/pokemap-2
@PokemonGoers/hashpokemongo
@PokemonGoers/predictpokemon-1
@PokemonGoers/predictpokemon-2 
Please suggest domain names. (Check for availability first!)

**Comment by bensLine** [comment]
- pokepoint.info, .io
- pokedexmap.org, .info, .io
- pokeinfo.org, .io
- pokecompanion.com, .org, .info, .io
- pokemaster.com, .info
- pokegoers.info, .org, .io

**Comment by MajorBreakfast** [comment]
Again: Check availability. It's important!

@bensLine pokemaster.com is not available. I haven't checked the others.

**Comment by bensLine** [comment]
@MajorBreakfast i checked them on godaddy.com, they are available for sale. prices vary. this one is quite expensive, though.

**Comment by gyachdav** [comment]
we poor 😆  so domains that are only available for sale are irrelevant. 

Anyways we're not a commercial entity so no need to check .com domains.

**Comment by jonas-he** [comment]
There is the possibility to go for a free alternative... however this comes with the cost of a little postfix. http://freedns.afraid.org
There you can set up free subdomains for any of the domains listed (e.g. *.ftp.sh)

**Comment by gyachdav** [comment]
We will have some money to buy a domain but definitely not more than tens of euros. Stay lean 😄

**Comment by mfkaptan** [comment]
- pokeoracle
- predictemall
- pokedict
- pokegopoint

**Comment by AlexanderLill** [comment]
See #62 for finding a domain name.
