### ISSUE TITLE
First deployment

### ISSUE THREAD

**Issue by MajorBreakfast** [PokemonGoers/Catch-em-all#21]
After we've decided all hosting related choices in #20, we'll be able to do our first deployment.
- [x] Make our app a docker container
- [x] Deploy to chair's docker node
- [x] Add link to our README

**Comment by johartl** [comment]
I started working on the Docker topic. See branch `deployment` for further details. The current setup looks as follows.

There will be 3 docker containers
1. **app** Web app of Project E which also includes the two PokeMaps as npm requirements. Within the repository of Project E there is also a small node server which serves static assets and redirects HTTP requests to the `/api` route to the **api** docker container (see #28).
2. **api** The PokeData project which serves as a backend for the **app** container. Luckily, the guys from the PokeData team already created a Dockerfile which we will use. Currently we assume that the work of Project B and Project C will be somehow included into this container already.
3. **db** MongoDB container.

The 3 containers are linked together using Docker Compose. So ideally we will just need to run `docker compose up` which should produce a running app including backend and database.

The Travis CI build is also already set up and running (unfortunately we have no test cases yet).

@sacdallago How exactly will the deployment to the chair's docker platform work? And are we just talking about the final deployment (when the seminar is over) or can we also use it as CI server during the development?

**Comment by sacdallago** [comment]
@johartl would you care to look if it is possible to user docker compose with [docker hub'd automatic builds](https://docs.docker.com/docker-hub/builds/) and docker cloud automatic deployment (which is just spawning the built from docker hub, so if you solve docker hub, docker cloud should be ok with it)?

SOOOOOO.. there's still no chair :D it's my servers, still. And for now it's like this: PR get's approved to develop/master --> automatic build on docker hub to tags develop/latest --> automatic redeploy on docker cloud (which uses my server as a node).

I can set the container on the node (my server in the future the chair's server) to always redeploy on the same **port**, and then use nginx on the server to route a specific DNS entry to that port (aka request to `example.com` --> DNS resolve to `198.252.78.170` --> reverse-proxy to `localhost:3030`) via internal reverse-proxy (I'm doing this for http://cell.dallago.us , which is actually http://cellmap-9af2e29c-1.835b2249.cont.dockerapp.io:3030 ).

Find out the docker compose story and we can look for the next step

**Comment by sacdallago** [comment]
Actually:

Why would you need to compose Mongo, API + website?
- Mongo we will use a dedicated server, and you won't need mongo because the API will use mongo, but the website will use the API
- API will always be up and independent of the website

So ultimately the only container you need is for the website. I suggest to drop the compose idea

**Comment by johartl** [comment]
Thanks for clearing things up @sacdallago. The idea with using nginx as reverse proxy sounds reasonable!

Why compose? Why three containers?
- **Configuration.** compose handles the dependencies between the containers. You can define through which ports the three containers communicate with each other while only exposing one port to the outside world.
- **Consistency.** I feel like if we're already using docker, why not use it for mongo as well? After all, everything is a container, right? ;)
- **Testing.** Using compose everyone can set up their isolated test environment. If we plan to have some integration tests that require both the frontend web app and the backend api to be set up this can be easily done.

Don't get me wrong here. That's what I had in mind when i started using docker compose. But I'm always a big fan of dropping stuff that's not needed (anymore). So if you think that the web app container is all we need and you'll be able to set up the entire project from that, then I'm happy to take back that compose idea.

**Comment by sacdallago** [comment]
I agree on all points: the composer idea is great in dev, but for the pipeline we have (already setup) it's superfluous :)

For me all I need is the dockerfile to build the webapp (so that it can automatically build on hub and depoy on cloud). But in general having a one-click solution with API, storage and webapp is definetly good for other people to try out or (as already said) dev.

I'm just trying to be [lean](http://hackerchick.com/agile-vs-lean-yeah-yeah-whats-the-difference/)

**Comment by johartl** [comment]
@sacdallago I made some good progress today in terms of deployment.
- The Ionic app will now be packaged for use as web app.
- A docker container is created containing the packaged web app and a node server that serves the app on port 8080. The PokeData backend can be reached at the `/api` route.

What else do you need me to do? How will the docker image be published to Docker Hub? Automatically on every commit/PR or do we need to trigger the build explicitly? If you want to add me to the pokemongoers organization my username is johartl.

Waiting for instructions :)

**Comment by sacdallago** [comment]
@johartl 
1. Added
2. Triggered first built https://hub.docker.com/r/pokemongoers/catch-em-all/builds/
3. What do I need to run it actually (env variables?)

**Comment by sacdallago** [comment]
P.S.: Builds on merged PRs on develop and master. You are gonna have two endpoints, the master to be used as production, the develop for testing.. Like in real life :D

**Comment by johartl** [comment]
Thanks for adding me!
The necessary changes are on the ionic2 branch and need to be merged to develop first (PR #33  has been opened just a few minutes ago). Sorry, I should've probably mentioned that.
The docker container exposes port 8080, hence, it can be run as follows
`docker run -p 80:8080 pokemongoers/catch-em-all` on port 80.

By default it uses the API endpoint at `pokedata.c4e3f8c7.svc.dockerapp.io:65014`. This can be changed like so
`docker run -p 80:8080 -e API_HOST=api.pokedata.com -e API_PORT=80 pokemongoers/catch-em-all`

**Comment by sacdallago** [comment]
@johartl nice! I fucked up the chair's servers this morning (not like, I did do anything extrorindarily dangerous... but it feels like having a ferrari with a fiat 500 engine :dash: ), so now they need to fix an implement the changes that I asked for :D hopefully we have a nice an clean solution soon, then I'll send you the links to the various things

**Comment by johartl** [comment]
@sacdallago The ionic branch with the required deployment changes has just been merged. This means we now have a [successfully built docker container](https://hub.docker.com/r/pokemongoers/catch-em-all/builds/) :)
Is there anything else you need me to do? Or are we just waiting for the server to be fixed? :D

**Comment by sacdallago** [comment]
@johartl just wait :) I'll update everyone once everything is up and running

**Comment by sacdallago** [comment]
The chairs VM is giving me a hard, hard time.

So in the meantime, Christian's servers it is:

http://catch-em-all-0a600d65.c65978f4.svc.dockerapp.io:4898/

For now only develop, as latest/master doesn't exist as a tag anyway :)

**Comment by johartl** [comment]
Since we have a running app I will close this now.
For all topics related to hosting (e.g. domain and SSL certificate) please see #20.
