### ISSUE TITLE
PokeMap JavaScript API

### ISSUE THREAD

**Issue by MajorBreakfast** [PokemonGoers/Catch-em-all#24]
@PokemonGoers/pokemap-1 
@PokemonGoers/pokemap-2 

The objective of this issue is to define the API surface between the pokemon map and the rest of the app. All suggestions are welcome!
## API Draft

https://github.com/PokemonGoers/Catch-em-all/issues/23 outlines the PokeData JavaScript API. All classes outlined in that API draft are assumed to exist as specified.

class `PokeMap` extends `EventEmitter`*
- `PokeMap(htmlElement, { filter, tileLayer, apiEndpoint, websocketEndpoint })` constructor that initializes the app at the given `htmlElement`.
  - `filter` The parameter from the `filter(..)` method below.
  - `tileLayer` e.g. `http://{s}.tile.opencyclemap.org/transport/{z}/{x}/{y}.png`
  - `apiEndpoint` The URI where the PokeData api runs on e.g. `http://pokedata.c4e3f8c7.svc.dockerapp.io:65014`.
  - `websocketEndpoint` The URI where the PokeData websocket runs on e.g. `http://pokedata.c4e3f8c7.svc.dockerapp.io:65024`. You can connect to the sockets for mobs and sentiments at `websocketEndpoint + '/mobs'` and `websocketEndpoint + '/sentiment'`, respectively.
- `goTo({coordinates, zoomLevel})` animates the map from the current position to the designated location and zoom level
  -  `coordinates = {latitude, longtiude}`.
  -  `zoomLevel` Defined here http://wiki.openstreetmap.org/wiki/Zoom_levels
- `navigate(start, destination)` Calculates and displays a route (a line one the map) from the `start` location the the `destination` location. Both parameters are objects `{latitude, longitude}`.
- `clearRoutes()` Removes the previously drawn routes from the map.
- `filter({ pokemonIds, sightingsSince, predictionsUntil })` applies filter options to the map.
  - `pokemonIds` Array of Pokemon IDs which are shown (applies to predictions and sightings) on the map. If `null` show all 151 Pokemon.
  - `sightingsSince` Time in seconds for which sightings (includes mobs) in the past are shown. If `0` don't show any sightings.
  - `predictionsUntil` Time in seconds for which predictions are shown. If `0` don't show any predictions.
#### Events
- `pokeMap.emit('click', pokePOI)` emitted after a point of interest was clicked and the card with details should open. `PokePOI` can be sightings, mobs or predictions.
- `pokeMap.emit('move', { coordinates, zoomLevel })` emitted when the user manipulates the map.

`*` Some basic `EventEmitter` implementation like https://github.com/scottcorgan/tiny-emitter
### September 14th
- Removed `updateTimeRange` method and introduced more general `filter` method.
- Removed `coordinates` from constructor's parameters because at the time of initialization we may not know the user's location yet. The map should then just be initialized to an arbitrary location (like showing the entire globe).
- Added parameter `zoomLevel` to `goTo` method. The reason for this is that a location like `Munich` should be shown as a larger part of the map whereas `TU München` results in a smaller part. We will calculate the appropriate zoom level for this.
### September 17th
- Added `tileLayer` parameter to contructor. See https://github.com/PokemonGoers/PokeMap-2/issues/25
### September 22th
- Added calls `navigate` and `clearRoutes`.
### September 24th
- Added `websocketEndpoint` to constructor.

**Comment by gqinami** [comment]
Hello guys, 

We, from team PokeMap1 implemented a angular directive to display a map. You can pass all the requested attributes to it, and it will respond automatically to your changes of these attributes. If you have any other suggestions for other attributes, please let us know.

Concerning the event of the clicked pokemon, you'll be able to handle it in your angular controller. 

Here is the example of usage

`<pokemap
                     lat="center.lat"
                     lng="center.lng"
                     zoom="center.zoom"
                     maxzoom="maxzoom"
                     pois="pois"
                     tileLayer="http://{s}.tile.thunderforest.com/cycle/{z}/{x}/{y}.png"
                     ......
            >
            </pokemap>
`
Thanks

**Comment by johartl** [comment]
@PokemonGoers/pokemap-1 
I'm not sure how we are supposed to integrate your map into our project. 
I mean, simply adding `<pokemap ...></pokemap>` to our HTML certainly won't do the trick ;)
So which steps exactly do we need to perform in order to get the map running. I saw that you're using webpack as well as gulp. So is there some kind of build process involved?

Ideally you have a `index.js` which exports a class/function just like the `PokeMap` class defined above. 

``` (javascript)
// index.js
(function(root) {

  class PokeMap {
    constructor(htmlElement, options) {
    }

    //...
  }

  if (typeof define === 'function' && define.amd) {
    // AMD
    define([], function() { return PokeMap; })
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS
    module.exports = PokeMap;
  } else {
    // Browser global
    root.PokeMap = PokeMap;
  }

})(this);
```

In your `package.json` you would also need to specify `index.js` as entry point:

``` (javascript)
{
    //...
    "main": "index.js"
    //...
}
```

And then we would do

``` (javascript)
var PokeMap = require('pokemap-1');
var pokeMapHtmlNode = document.getElementById('poke-map');
var map = new PokeMap(pokeMapHtmlNode, { /* options */ })
```

Afterwards you would be able to publish your map as npm package.

Here are a few resources that might help you get started. Please don't hesitate to ask questions!
- http://ifandelse.com/its-not-hard-making-your-library-support-amd-and-commonjs/
- https://docs.npmjs.com/getting-started/creating-node-modules
- https://docs.npmjs.com/getting-started/publishing-npm-packages

I suppose this information might also be interesting for @PokemonGoers/pokemap-2

**Comment by johartl** [comment]
@MajorBreakfast 

> How is the zoomLevel defined?

Both groups are using Leaflet which comes with a definition of a zoomLevel.

> Should we pass an html element into the constructor or do you want to create it and we append it?

Leaflet has a constructor function 
`L.map( <HTMLElement|String> id, <Map options> options? )`
Hence, I would pass the HTML node directly.

> `displayPokePOIs(pokePOIs)` Displays the passed in array of PokePOIs

I'm not sure what this function is supposed to do? How does the map display the POIs? By zooming to their location? And why does the function take an array rather than a single POI?

**Comment by MajorBreakfast** [comment]
@johartl About `PokeMap#displayPokePOIs(pokePOIs)`. The idea was a way to specify all PokePOIs at once where the new ones replace the old ones. A function like that is only necessary if the map doesn't talk to the PokeData JSON API. I think that's the case now, though.

@gqinami You're free to use Angular internally for testing and stuff but you should not expose it. We're using Angular 2 in our project BTW. However, leave the UI to us, thus no need for Angular.

**Comment by farisca** [comment]
PokePOI object only contains coordinates? How can we know which Pokemon to show on the map?

**Comment by MajorBreakfast** [comment]
@farisca `PokePOI` is an abstract super class of `PokemonSighting`, `PekomenPrediction`, `PokeMob` o.O

**Comment by farisca** [comment]
Oops, I totally missed that. Sorry, my fault.

**Comment by oleks-fedotov** [comment]
@MajorBreakfast will it be ok for you to have an angular 2 component with a map incapsulated? Otherwise you'll need to write your own component to wrap the map-module or write the part of the project in VanillaJS using map-module

**Comment by MajorBreakfast** [comment]
@WoH @johartl Can you comment? I've still no good picture about where the map functionality ends and our app UI starts...

**Comment by WoH** [comment]
Just like @ukrainian256  proposed, by importing a Component in our main page and displaying it in the template of our main page.

> I mean, simply adding <pokemap ...></pokemap> to our HTML certainly won't do the trick ;)

Just like that :smile:

**Comment by farisca** [comment]
PokeMap-2 is using the approach described by @johartl without any angular components.

**Comment by farisca** [comment]
Also, is the time slider your task or ours? 

We already implemented it:

<img width="598" alt="screen shot 2016-09-09 at 13 31 16" src="https://cloud.githubusercontent.com/assets/6860946/18385705/8c4d3d5c-7692-11e6-8419-17d6210da56f.png">

However, in this case we would need to have an event emitted after the user moves the slider (after which you call the method displayPokePOIs with the new pokePOIs?)?

**Comment by WoH** [comment]
I think this should ideally be part of the Ionic2 App, we were planning on a Floating Action Button that opens Popover. So we would take care of that.

**Comment by johartl** [comment]
> Just like @ukrainian256 proposed, by importing a Component in our main page and displaying it in the template of our main page.

I think this approach is bad for a couple of reasons
- This will only work if we both use angular and only if the two angular versions are compatible. The PokeMap team is using Angular 1 whereas we are using Angular 2. I doubt that importing the A1 component into an A2 project will just work out of the box. 
- The PokeMap2 team also managed to export their module properly. And we don't want to support two different ways of including the map. 
- It exposes the implementation details of the map and thus creates tight coupling. To us it shouldn't really matter how you implemented the map, whether it's Angular, jQuery or just vanilla JS. As long as the interfaces are clear you can use any framework you like :)

If I find the time I will submit a PR for the @PokemonGoers/pokemap-1 repository today with a wrapper implementation that can help you get started.

> I think this should ideally be part of the Ionic2 App, we were planning on a Floating Action Button that opens Popover. So we would take care of that.

I agree.

**Comment by johartl** [comment]
@farisca 

> However, in this case we would need to have an event emitted after the user moves the slider (after which you call the method displayPokePOIs with the new pokePOIs?)?

This was the plan initially but we deviated from that. As you will be talking to the PokeData api directly I would propose that you will receive the information about the time range from us. So we add a `timeRange` object which is also being passed into the PokeMap constructor.

```
PokeMap(htmlElement, {
    coordinates: {longitude, latitude},
    zoomLevel,
    timeRange: {from, to}
})
```

And then I would add another method which we will use to update the time range.

`updateTimeRange(from, to)`

So the information flow with regards to the time range would be
1. We call the `PokeMap` constructor with a predefined time range (e.g. next 15 minutes)
2. User changes the time range using the slider
3. _CatchEmAll_ handles the slider change event and calls `pokeMap.updateTimeRange(newFrom, newTo)`
4. _PokeMap_ updates the view according to the new time range

I would also propose that `from` and `to` are numbers representing the time in seconds from now. Thus, `updateTimeRange(60, 180)` should display all predictions between 1 minute from now and 3 minutes from now.

What do you think?

**Comment by WoH** [comment]
@johartl 
- time range should honestly be a bit less fine-tuned.
- zoomLevel should probably be none of our business
- we need to pass a callback to handle the User clicking on a Pokemon

**Comment by johartl** [comment]
@WoH 

> time range should honestly be a bit less fine-tuned.

Sure. So minutes it is?

> zoomLevel should probably be none of our business

Also okay. I suppose the two PokeMap teams have already implemented some kind of zooming mechanism anyway. So we should consider the zooming entirely as part of their project.

> we need to pass a callback to handle the User clicking on a Pokemon

The idea by @MajorBreakfast was to use an event emitter for this.

`pokeMap.emit('click', pokePOI)` to trigger the event and
`pokeMap.on('click', pokePOI => console.log('clicked on', pokePOI.name))` to listen to clicks

Same goes with `pokeMap.emit('move', {latitude: 47, longitude: 11})`

**Comment by WoH** [comment]
@johartl 
My bad, didn't read carefully enough.
Probably Minutes, but I won't say anything until I see the results of the Predictions Team.

**Comment by farisca** [comment]
I want to be sure one more time: we (pokemap) are contacting PokeData API? Then why should we emit "move" event? If the map is moved, then **we** should fetch data for the new area? 
Also, the methods defined in the first comment don't make sense anymore? For example, why would you need a public method `displayPokePOIs(pokePOIs)` if we fetch the data now?

I'm sorry if these questions have already been answered somewhere :D

**Comment by johartl** [comment]
@farisca 
1. Yes you are right. You will be contacting the PokeData API directly. 
2. If the map is moved you will need to fetch the new data on your own and display new Pokemon accordingly. But it can still make sense to notify the CatchEmAll project about the changes. One scenario that I can think if would be that we update the URL every time the map changes. This way you can share links to your friends with a specific location. Have a look at this google maps link that will take you to the Garching campus directly:
   https://www.google.de/maps/@48.2632522,11.6685135,17.25z
3. `displayPokePOIs(pokePOIs)` is not needed anymore. I will update the description in the first post.

Thanks for your questions. The interface is still a draft and nothing is set in stone. So your suggestions are very appreciated :)

**Comment by johartl** [comment]
I updated the draft in the first post. A summary of the changes I made:
- removed `displayPokePOI` method
- added `updateTimeRange` method
- renamed to `clickedPokePOI` event to `click`
- added `apiEndpoint` to the constructor. This parameter will be passed into the docker container and thus we should all use the same endpoint.
- added `timeRange` to the constructor.
- removed `zoomLevel` from the constructor and the `goTo` method. As @WoH pointed out that's not really our business.
- removed the `coordinates` and `zoomLevel` getters. I suppose we don't really need them either.

I hope that now the interface contains all we need but not more than that.

**Comment by farisca** [comment]
Thanks for the updated version of the interface description! Should we also define a method `showPokeMobs()` which should trigger the display of mobs?

Also, regarding the `timeRange` parameter: if it has values `{2, 5}` then we show the predictions between these two points in the future. But what about the sightings. Should we show all of the sightings all the time, or the `timeRange` fields can have negative values?

**Comment by johartl** [comment]
> Thanks for the updated version of the interface description! Should we also define a method showPokeMobs() which should trigger the display of mobs?

I'm not sure what you mean exactly. Does this method enable and disable the display of PokeMobs? Personally, I would just show them at all times because they probably don't happen too often. If the PokeMobs turn out to distract the user a lot we can still think about a filter option later. 

> Should we show all of the sightings all the time, or the timeRange fields can have negative values?

The time slider we have in our app right now only lets you select positive values but we can certainly change that. I wasn't aware of data from the past. Since your team is talking to the PokeData API you should know best what data you are going to display and how it can be filtered. So maybe just tell us what time-based filter options we need to support.

Thanks for your input @farisca! 

Edit: Also note this issue I found: https://github.com/PokemonGoers/PokeMap-1/issues/8

**Comment by farisca** [comment]
Regarding PokeMobs, your comment totally makes sense. 
Regarding time slider: let's follow the issue you referenced.

Btw, regarding PokePOI, PokemonSighting etc classes: should we create them or you already have them somewhere (in this case, how should we import them?)

**Comment by johartl** [comment]
The PokePOI, PokemonSIghting and other classes from #23 are very outdated. Please don't pay too much attention to them for now. 
Ideally these objects are simply the JSON you receive from the PokeData API. So you should be able to pass these objects to us directly and there is no need to create classes.
I'm currently collecting information from each project how a PokeSighting, PokeMob and PokePrediction object will look like and summarize them soon.
We also had a hackathon yesterday where we finalized(*) our map filter options. This will change the API from above slighty (the `updateTimeRange` method will be replaced with a more general filter method). I will update this soon and let you know

(*) I probably overuse this word a lot. I'm having a hard time trying to to handle all the dependencies and interfaces between the projects. But we're finally getting somewhere and I hope you apologize the frequent changes :)

**Comment by johartl** [comment]
@PokemonGoers/pokemap-1 
@PokemonGoers/pokemap-2 
I updated the PokeMap interface. You now also find a changelog that summarizes the changes.

**Comment by johartl** [comment]
@PokemonGoers/pokemap-1 
@PokemonGoers/pokemap-2 
Please check the updated PokeMap interface.

**Comment by sacdallago** [comment]
Can this be closed, if everything has been sub-issued?
