### ISSUE TITLE
(Persistent) Bottom Sheet

### ISSUE THREAD

**Issue by WoH** [PokemonGoers/Catch-em-all#27]
- Upon clicking a Pokémon on the map, a swipeable bottom sheet should appear
  (implementation as bottom footer nav bar?)
- When swiped up, a card-like summary of the prediction should be shown
- WIP

**Comment by johartl** [comment]
Anyone interested? Maybe one of @mfkaptan @Georrgi @Lugitan?

**Comment by AlexanderLill** [comment]
@johartl this can be closed once #87 is merged, right?
