### ISSUE TITLE
Running the demo fails

### ISSUE THREAD

**Issue by gyachdav** [PokemonGoers/Catch-em-all#41]
Running without Docker. Please advise.

Log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.7.3
3 info using node@v5.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Catch-em-all@0.0.0~prestart: Catch-em-all@0.0.0
6 silly lifecycle Catch-em-all@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle Catch-em-all@0.0.0~start: Catch-em-all@0.0.0
8 verbose lifecycle Catch-em-all@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle Catch-em-all@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/guyyachdav/Sites/Catch-em-all/server/node_modules/.bin:/usr/local/bin:/Users/guyyachdav/Library/Haskell/bin:/opt/local/bin:/opt/local/sbin:/System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin:/opt/local/bin:/opt/local/sbin:/usr/local/mysql/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/local/ncbi/blast/bin:/usr/texbin
10 verbose lifecycle Catch-em-all@0.0.0~start: CWD: /Users/guyyachdav/Sites/Catch-em-all/server
11 silly lifecycle Catch-em-all@0.0.0~start: Args: [ '-c', 'node lib/main' ]
12 silly lifecycle Catch-em-all@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle Catch-em-all@0.0.0~start: Failed to exec start script
14 verbose stack Error: Catch-em-all@0.0.0 start: `node lib/main`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid Catch-em-all@0.0.0
16 verbose cwd /Users/guyyachdav/Sites/Catch-em-all/server
17 error Darwin 13.4.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v5.8.0
20 error npm  v3.7.3
21 error code ELIFECYCLE
22 error Catch-em-all@0.0.0 start: `node lib/main`
22 error Exit status 1
23 error Failed at the Catch-em-all@0.0.0 start script 'node lib/main'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Catch-em-all package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node lib/main
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Catch-em-all
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Catch-em-all
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by WoH** [comment]
@gyachdav 
Build worked fine using 6.5.0 just now, installed 5.8.0, tried again, failed.
Could you try to rerun using a later version if you are using a node version manager?
I already have issues using ES6 syntax with 5.8.0

> Catch-em-all\server\lib\main.js:17
> for (let signal of signals) { process.on(signal, closeApp) }
>      ^^^
> 
> SyntaxError: Block-scoped declarations (let, const, function, class) not yet sup                                                                                                                                                  ported outside strict mode

E: Also, maybe try deleting the node_modules folder and run npm install again.

**Comment by sacdallago** [comment]
I think it's not node related, guy doesn't have the env variables set.

You need and env file @gyachdav, I'll forward the mail where I got that, and please see the "API packaging" thread here to see how to spawn the instance using the env file, then let us know

**Comment by gyachdav** [comment]
resolved.
