### ISSUE TITLE
Time Filter Popover

### ISSUE THREAD

**Issue by WoH** [PokemonGoers/Catch-em-all#42]
A Popover to the Main(aka Map)-View.
Shows a simple Popover with a Slider for the days.
After a small debounce, the data is synced with a new Filter Object that is introduced in the Main Component.
Please let me know what you think.

For the lazy ones:
![2c578af559728c0a36945e0f9dbb6d7b](https://cloud.githubusercontent.com/assets/2697771/18387955/d338d11a-769f-11e6-8717-f1eeba35fb63.gif)

If you want to add anything or think that @sacdallago should never see [how bad it looks](https://github.com/PokemonGoers/Catch-em-all/issues/26#issuecomment-244591795) right now, please help me style it -> [PokemonGoers/Catch-em-all/tree/FilterPopover](https://github.com/PokemonGoers/Catch-em-all/tree/FilterPopover)

**Comment by WoH** [comment]
(without snaps)

![](https://i.gyazo.com/110621da6f0ac3319085370bd59e57de.gif)

**Comment by sacdallago** [comment]
@WoH this looks fancy AF

**Comment by WoH** [comment]
Closed for now, will come up when we make things pretty
