### ISSUE TITLE
Alpha

### ISSUE THREAD

**Issue by gyachdav** [PokemonGoers/Catch-em-all#48]
Hey there project E, 

Your demo seems to run nicely but currently there is not much to see 😆 

![image](https://cloud.githubusercontent.com/assets/4074881/18412746/3c98627e-779f-11e6-8382-6c0e6572df18.png)

Please take some time to merge your branches into develop so we (mentors) and other projects can see your progress and start giving you feedback.

**Comment by johartl** [comment]
Hi guy,
I thought I'll give you a quick overview over our current work progress.

### Deployment

The continous integration/deployment is fully set up. Once changes are pushed to develop or master a Docker container is automatically built and set up at http://catch-em-all-0a600d65.c65978f4.svc.dockerapp.io:4898/. Test cases are executed automatically as well. For more details see #21 and #20.

### App user interface

There are currently some active PRs which will be merged soon.
- #40 will add a navigation menu and and a about/impress page
- #46  will add a button for filtering the map

Also, #26 is still in development and will add a search bar for Pokemon and locations. With that I think we have the most important elements of our app shell set up.

### Integration of PokeData

The PokeData backend is fully integrated. For instance, you can try accessing `http://localhost:8080/api/pokemon` and it should give you a list of all Pokemon. We also wrote a client-side library for querying the API in #36.

### Integration of PokeMaps

There is some ongoing (constructive) discussion about an interface specification in #24. I submitted a PR in the PokeMap-2 repository to push the integration https://github.com/PokemonGoers/PokeMap-2/pull/33. If that goes through I will do the same for the PokeMap-1 project.
The @PokemonGoers/pokemap-2 is also working actively with us to implement the proposed interface. However, there is still some refactoring needed and currently we just get a "file not found" error when importing their project.
The @PokemonGoers/pokemap-1 team created an Angular1 directive to integrate the map. Unfortunately, we can't make use of this, so we're still waiting for them to properly export their map and implement the interface from #24. It also seems that only one person is contributing to the code base so the communication is a bit limited. Maybe you can give them a little push ;)

So I hope you can tell that even if there is not much to see when launching our app right now we're actively working on a couple of different topics and have also achieved a lot in terms of tooling and deployment.

You will be happy to hear that we will have a Hackathon next week at TUM with most team members attending. Once the date has been set we can let you know and maybe one of the tutors can attend the event as well.

**Comment by gyachdav** [comment]
Thanks for the prompt and detailed overview @johartl. Glad to see that you guys are following a plan that would keep you on track!

Im also glad to hear about the hackathon next week. Please let me know which day/s will it take place so we can move the Alpha release milestone due date accordingly.

> The @PokemonGoers/pokemap-1 team created an Angular1 directive to integrate the map. Unfortunately, we can't make use of this, so we're still waiting for them to properly export their map and implement the interface from #24. It also seems that only one person is contributing to the code base so the communication is a bit

I see the problem. Have you tried inviting pokemap-1 to your hackathon? Porbaly will be the most efficient catalyst to move past this road block. If they cannot join you on the hackathon then please suggest a due date for the module issue to be resolved and we will enforce it. 

btw, are you sure you got the project groups right? https://github.com/PokemonGoers/Catch-em-all/issues/24 refers to work done by [pokemap-2](https://pokemongoers.github.io/PokeMap-2/) I still didn't see where you have an active discussion with pokemap-1. All I could find [is a discussion](https://github.com/PokemonGoers/PokeMap-1/issues/10)  from 8 days ago.

All that said, we do need to see something. Even if you do not have the map components integrated it will still be good to see the structure of your web app, the navi components, headers, footers etc. please make those available in develop as soon as possible.

**Comment by johartl** [comment]
@gyachdav 
Yes, the active discussion part only referred to the PokeMap-2 team around @farisca who helped to refine the interface description and get rid of unnecessary parts :+1: Sorry if that was unclear.
The only two reactions by the PokeMap-1 team in that issue were focused around the Angular 1 directive and 3 or 5 days old. I'm also following the activity in their repository and there hasn't been a lot recently.
I will try to talk to them directly. Inviting them to our hackathon is also a good idea, thanks for the input! :+1:

**Comment by gqinami** [comment]
hey @johartl,

We from PokeMap-1 are re-writing our part of the app from scratch in plain JS since the Angular 1 directive provided by us in the beginning was not able to be integrated in the big app. We are writing it as per the specifications in this issue (https://github.com/PokemonGoers/Catch-em-all/issues/24). 
Regarding the activity, maybe you are watching only the develop branch activity :) but anyways, we will contact your team these 2-3 days in order to check if you can integrate our map in the full app. 

Best, 
PokeMap-1 team

**Comment by johartl** [comment]
@gqinami Yes Perfect!! :)
And yes I was in fact looking at your development branch but also at issues and PRs from your repository. Plus I rarely saw any input or sign of acknowledgement in #24 or https://github.com/PokemonGoers/PokeMap-1/issues/10 which made me question your activity. But I just checked again and found the other branches so sorry for the false accusations!
But if you could keep us updated about your progress every now and then that would really make things a lot easier :)

**Comment by johartl** [comment]
@gyachdav What exactly is your understanding of an Alpha release? Which features do you want to see implemented?

**Comment by gyachdav** [comment]
Alpha - An MVP we can all take a look at and appreciate what the main components are. 

The most important features would be:
- [x] Integration of at least one map component with main controls that interact with the component
- [x] Populating the wiki data
- [ ] Navigation
- [ ] Compatible across all devices

**Comment by gyachdav** [comment]
Please give a status update. hiw did the hackarhin go? How far are we from the MVP?

**Comment by WoH** [comment]
(1/5)
![pokedex](https://cloud.githubusercontent.com/assets/2697771/18608920/3b71fb56-7cf6-11e6-80c6-4bc71603271e.jpg)

Wiki Index Page by Me - Done and Merged
- [x] Add Page
- [x] Dynamic Search Bar
- [x] Felixble Boxes

Detail Page by @AlexanderLill and @philbu - WIP and should be ready by Monday
- [ ] Page and basic details
- [ ] Module that visualizes Evolitions in a Component
- [ ] Attack Component

**Comment by WoH** [comment]
(2/5)

![https://files.gitter.im/rostlabjs16projecte/Lobby/4qzb/20160913_121145.jpg](https://files.gitter.im/rostlabjs16projecte/Lobby/4qzb/20160913_121145.jpg)

Bottom Sheet by @johartl
- [ ] Component
- [ ] Shows infos about TLN in case of a Prediction
- [ ] Shows most important info about Pokemon

**Comment by WoH** [comment]
(3/5)

![https://files.gitter.im/rostlabjs16projecte/Lobby/1PiN/IMG_0642.JPG](https://files.gitter.im/rostlabjs16projecte/Lobby/1PiN/IMG_0642.JPG)

Redesigned Filter Popover, mostly @MajorBreakfast 
- [x] Tabs for Time and Pokemon filtering (in PR)
- [ ] Time: Customized Slider for Sightings
- [ ] Time: Customized Slider for Predictions
- [ ] Pokemon: Radio Buttons for type (selected, deselected, partially selected)
- [ ] Pokemon: List of currently shown Pokemon and Search Bar to add new ones

**Comment by johartl** [comment]
As for the PokeMap integration, I created two issues https://github.com/PokemonGoers/PokeMap-1/issues/15 and https://github.com/PokemonGoers/PokeMap-2/issues/35 to track what each team still needs to do to get the map running. 
From our side we're ready to integrate the map(s) once all issues have been resolved.

**Comment by WoH** [comment]
^ (4/5)

**Comment by WoH** [comment]
(5/5)
- @mfkaptan works on a favicon https://github.com/PokemonGoers/Catch-em-all/issues/49 here
- The domain war is still going on and as you suggested we will vote on Monday https://github.com/PokemonGoers/Catch-em-all/issues/62

**Comment by johartl** [comment]
#64 adds automated Android builds.

**Comment by johartl** [comment]
#65 integrates the first PokeMap.

**Comment by sacdallago** [comment]
@johartl can you invite me @gyachdav @goldbergtatyana and @juanmirocks to the hockeyapp distribution?

Through the emails from the emails you got from us will be good ;)

**Comment by johartl** [comment]
@sacdallago I invited both @gyachdav and @goldbergtatyana but I couldn't find yours and @juanmirocks's email address.

**Comment by AlexanderLill** [comment]
@PokemonGoers/catch-em-all @sacdallago @gyachdav can this issue be closed then?

**Comment by sacdallago** [comment]
@johartl email sent with the emails to be added to the hockeyapp - sorry for major delay
