### ISSUE TITLE
Logo / Favicon / Launcher icon

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/Catch-em-all#49]
We will need a logo that can be used both as favicon and launcher icon when installing the app on Android or iOS. Do we have someone who's really talented with Photoshop/Gimp/Paint?

**Comment by WoH** [comment]
I mean, I have some nasty Paint tricks up my sleeve. I saw some Pokémon themed favicons, but if we could get our own that'd be better.

**Comment by sacdallago** [comment]
Try to go CC0 and some minor PS, that's the easiest way :)
Pokedex themed?

**Comment by mfkaptan** [comment]
![image](https://cloud.githubusercontent.com/assets/3976573/18471533/13700f00-79bb-11e6-9d2e-49765dcfd3f6.png)

Not my work but it is free if we credit the author. Source: http://www.flaticon.com/free-icon/map_188983#term=pokemon&page=1&position=39

**Comment by mfkaptan** [comment]
![image](https://cloud.githubusercontent.com/assets/3976573/18471920/c1946170-79bc-11e6-855c-ad65122aa48f.png)

or

![image](https://cloud.githubusercontent.com/assets/3976573/18607944/1a9c023a-7ce4-11e6-9cbc-751510c6090b.png)

For emphasizing "prediction"

**Comment by mfkaptan** [comment]
![image](https://cloud.githubusercontent.com/assets/3976573/18607879/8e6031de-7ce2-11e6-9992-3561e11a83fe.png)

**Comment by mfkaptan** [comment]
Here is another one with my **amazing** skills, just think about the idea (trying to emphasize prediction again)

![image](https://cloud.githubusercontent.com/assets/3976573/18608001/a2aab602-7ce5-11e6-99ca-58d5cd02ddb6.png)

**Comment by sacdallago** [comment]
I likey likey n2 of https://github.com/PokemonGoers/Catch-em-all/issues/49#issuecomment-246653595 and https://github.com/PokemonGoers/Catch-em-all/issues/49#issuecomment-247765006

But rather the one with the magic sphere. You can put this up to vote one Monday at the lecture joint with the domain name

**Comment by johartl** [comment]
According to the [poll](http://www.easypolls.net/poll.html?p=57def23ee4b08db0f7e380a6) we have a winner.

![](https://cloud.githubusercontent.com/assets/3976573/18608001/a2aab602-7ce5-11e6-99ca-58d5cd02ddb6.png)

@mfkaptan Can you export this as favicon. A higher resolution would also be appreciated.

Edit: We need at least two versions:
- **Icon** 192x192 (square) for xxxhdpi.
- **Splash screen** 1280x1920 for xxxhpdi.

**Comment by MajorBreakfast** [comment]
👍

**Comment by johartl** [comment]
@mfkaptan Are you on this?

**Comment by mfkaptan** [comment]
I am.Currently boarding on a plane. I will update you asap.

**Comment by mfkaptan** [comment]
> Edit: We need at least two versions:
> 
> Icon 192x192 (square) for xxxhdpi.
> Splash screen 1280x1920 for xxxhpdi.

Do we need any other versions?

**Comment by johartl** [comment]
@mfkaptan The other resolutions (xxxhdpi, xxhpdi, xhdpi, and so on) will be rendered automatically by Ionic from the large resolution.So these two are just fine.
Did you manage to convert the logo?

**Comment by sacdallago** [comment]
@mfkaptan news?

**Comment by mfkaptan** [comment]
@johartl @sacdallago I managed to create the logos, where should I upload them?

**Comment by johartl** [comment]
How about here? Just drag+drop them into the input field.

**Comment by mfkaptan** [comment]
Sorry, I was on a mobile device when I asked. Here you go:

favicon.png
![favicon](https://cloud.githubusercontent.com/assets/3976573/19023947/843ed768-88fa-11e6-922d-430ce78c5b44.png)

splashscreen.png
![splashscreen](https://cloud.githubusercontent.com/assets/3976573/19023951/9915f6e4-88fa-11e6-9f51-6620b34cc85f.png)

And another one (600x600) in case we need for something else:
![logo600](https://cloud.githubusercontent.com/assets/3976573/19023964/c8137a52-88fa-11e6-82cd-d0cc838e1247.png)

**Comment by sacdallago** [comment]
Amazing!
