### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by philbu** [PokemonGoers/Catch-em-all#51]
## Legal information

@gyachdav We might need help here. Inspired by our predecessors (got.show) I created the main concept of our about page. They got an attribution page as well and I guess we'll need this for ours too.
By German law it is prohibited to have a website without an "Impressum" (that's a legally required statement of the ownership and authorship of a website). I'm not sure how other countries handle it and if it's fine with just linking the rostlab website. Do you have any further information about this topic?
## Design

@PokemonGoers/catch-em-all It's not that important but you can post any idea you got for creating a good Pokémon feeling on the about page here.

**Comment by sacdallago** [comment]
@philbu nice job, I'm gonna go through the legal text in detail later, but just a note on the teams:
- We will also add a few people that helped us from being the curtains (Dr. Lothar Richter, Timothy Karl, Prof. Burkhard Rost )
- @gyachdav what's the verdict on _that_ logo?
- The ordering of the names in the first section should be: Guy, Tatyana, me, Juanmi :)
- Potentially also students should be able to put the link to their private websites etc. For this one I suggest to already put links to "#" for everyone and then if  you could show here (C/P the LOC of the right file) where this can be changed, and everyone will open a PR requesting the change. It's, I believe, the most elegant way (and less work for you)

**Comment by gyachdav** [comment]
@sacdallago where can I see the logo?

**Comment by gyachdav** [comment]
@philbu very nice first try for the about page. Please start correcting for some typos and text formatting.
- [x] As for the imprint please use the exact same one used at https://www.got.show/imprint. 
- [ ] Make available a section for the privacy policy for now you can model it after https://www.got.show/privacy. I will start a separate issue in which we will collect info before generating a final text for the privacy policy. 
- [x] Make sure that you reference CC3.0

**Comment by philbu** [comment]
#54 Updated the about page and created the imprint page. Typos aren't fixed yet.

**Comment by johartl** [comment]
What's the state here @philbu?

**Comment by WoH** [comment]
I'll close this now unless someone decides this is still needed, since there was no response

**Comment by gyachdav** [comment]
request from iteratec:

Could you please change Iteratec in iteratec without capital „I“.
„We want to thank our sponsor Iteratec for providing the domain, hosting and some interesting insights into their company.“

**Comment by WoH** [comment]
Done, https://github.com/PokemonGoers/Catch-em-all/commit/97ba19bff9ae690e4d65c258651aab4d212ccd39
