### ISSUE TITLE
Set up CI server and host app

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/Catch-em-all#6]
This issue consists of a few activities:
- Research and select a provider for free server hosting.
- Install required packages and libraries on the server.
- Set up a Continuous Integration process that
  - Fetches the sources from each project
  - Executes test cases (if available)
  - Triggers the build process, e.g. transpile ES6/TS/Sass sources, optimize and uglify the code, bundle the application ...
  - Deploys the app onto the running system

**Comment by sacdallago** [comment]
Docker might be something you want to look into. If you use docker, we can ship the app on our servers

**Comment by MajorBreakfast** [comment]
Let's use travis ci like everyone. Our project is open source, so it's free.

**Comment by MajorBreakfast** [comment]
#18 adds CI to our project.

Fetching the sources from the other projects could be done via git at first. It is possible to specify git dependencies in `package.json`. Later on we should help the other teams with publishing their projects to npm and let them define a public API that we can use. Then, we can switch to npm package dependencies with proper semver compliant versioning.

**Comment by sacdallago** [comment]
I would close this issue and open up one for the hosting once we have a prototype. Opinions?

**Comment by MajorBreakfast** [comment]
Follow up issue about hosting #20

@sacdallago Don't close before follow up issues are created ;)
