### ISSUE TITLE
Find a domain name

### ISSUE THREAD

**Issue by AlexanderLill** [PokemonGoers/Catch-em-all#62]
Let's find an awesome domain name for our project (continuing the discussion from #20)

A few notes first:
- Please check the availability before you suggest a name
- The chair does not have a lot of money to buy it (keep it max. in "tens of euros")
- @sacdallago mentioned that the name should not contain TUM

The following list contains all suggestions; the checked crossed items are not options anymore. Let me know which suggestions I should add, and if any of those suggestions are not available any more or how much they would cost)
- ~~pokeTUM.com~~ (OUT: "TUM" in name)
- pokemon.rostlab.org
- Poke.map (?)
- poke.go (?)
- poke.point (?)
- pokepoint (~~.com~~, **.info**, **.co**, .io)
- pokemap24 (**.com**, **.net**, **.de**, .io)
- pokesnag (**.com**, **.net**, **.de**, .io)
- pokedexmap (**.de**, **.org**, **.info**, .io)
- pokeinfo (**.org**, .io)
- pokecompanion (**.com**, **.net**, **.de**, .io)
- pokemasters (**.info**, .io)
- pokegoers.info, (**.de**, **.org**, .io)
- pokeoracle (**.net**, **.de**, .io)
- predictemall (**.com**, **.net**, **.de**, .io) 
- pokedict (**.com**, **.net**, **.de**, .io) 
- pokegopoint (**.com**, **.net**, **.de**, .io)

Please see https://github.com/PokemonGoers/Catch-em-all/issues/62#issuecomment-247763820

Let's find more suggestions until I'd say wednesday (Sept 21st), and then we could vote on the result :)

@PokemonGoers/pokedata
@PokemonGoers/pokemap-1
@PokemonGoers/pokemap-2
@PokemonGoers/hashpokemongo
@PokemonGoers/predictpokemon-1
@PokemonGoers/predictpokemon-2 
@juanmirocks @sacdallago @gyachdav

**Comment by mfkaptan** [comment]
> Poke.map
> poke.go
> poke.point

I'm not sure if those extensions are possible.

**Comment by mfkaptan** [comment]
I have updated the suggestion list with availability. 
- **Bold** extensions are available under **$10-$15** per year.
- .io extensions are mostly available more than $30 per year.
- Other extensions such as .top, .co, .eu, .tech and .rocks :guitar: are available for most suggestions under $10 per year.

**Comment by johartl** [comment]
Final result of the domain poll

![poll](https://cloud.githubusercontent.com/assets/12528430/18685716/7eb63de8-7f79-11e6-9285-8d58f5d39ccb.png)
- **pokeoracle.de** (5 EUR/yr)
- **pokeoracle.net** (11.68 EUR/yr)

How should we proceed? @gyachdav are you gonna take care of the next steps?

**Comment by MajorBreakfast** [comment]
Because it was mentioned in today's seminar session: Everyone just selected the domain names they like, we didn't rank them. Should we do a second round with just the best 3 domain name candidates? Just an idea, tell me what you think.

**Comment by phdowling** [comment]
Sounds like a good idea to me. Three candidates, one choice per vote only?

**Comment by johartl** [comment]
@mfkaptan What's the status here? Can we close the poll?
http://www.easypolls.net/poll.html?p=57e3e857e4b020885be6111d

**Comment by mfkaptan** [comment]
Seems like we have a tie between `predictemall.com` vs `pokegoers.de`. What
is your solution?

**Comment by sacdallago** [comment]
I like them both 💃  Maybe tending slightly more to the _predictemall_

**Comment by mfkaptan** [comment]
@gyachdav I closed the poll, here is the last result:
![image](https://cloud.githubusercontent.com/assets/3976573/18871055/e010caec-84b3-11e6-9056-453f410a9335.png)

**Comment by goldbergtatyana** [comment]
I see undecided between pokegoers.de and predictemall.com (both 35%).

What is the final solution @mfkaptan ? Another poll :-D ?

**Comment by mfkaptan** [comment]
> What is the final solution @mfkaptan ? Another poll :-D ?

@gyachdav @sacdallago What do you think? Should I send another poll link to googlegroups?

**Comment by semioniy** [comment]
Somebody, just throw a coin)

**Comment by mfkaptan** [comment]
Or maybe let's go with predictemallpokegoers!.de with exclamation mark in it. Oor maybe we can do a poll to decide if we should do an another poll (pollception).
Jokes aside, I think one final poll is the answer.

**Comment by MajorBreakfast** [comment]
Since our app is in English IMO a ".com" domain is more favorable.
We could do another poll with just two choices: "predictemall.com" "pokegoers.de"

Also some rumbling: "goer" is not a word. "predictemall" reads like "predict e-mall" (mall as in shopping center). Haha :) (Yep, I voted for "pokeoracle")

**Comment by juanmirocks** [comment]
My 2 cents: 1) we want a .com or .net for an international audience. 2) I
also don't get / cannot parse "predictemall.com"

**Comment by gyachdav** [comment]
can you keep pokepoint in the next and last poll? 

btw, all .com suffixes will probably be expensive

**Comment by AlexanderLill** [comment]
@gyachdav see https://github.com/PokemonGoers/Catch-em-all/issues/62#issuecomment-247763820 for some price ranges.

Which pokepoint do you mean btw? .co? .info?

btw what a waste of a domain ... xD http://pokepoint.com/#

**Comment by jonas-he** [comment]
@juanmirocks the original theme song for the pokemon cartoon series did contain the phrase "gotta catch 'em all" (refer to https://www.youtube.com/watch?v=lrHJhKEtQEI) and since then it was a slogan in the whole franchise. "predictemall" would then read like "predict em all" accordingly.

**Comment by gyachdav** [comment]
whatever is available. .info sounds more appropriate.

**Comment by juanmirocks** [comment]
@jonas-he that makes sense -- but didn't get that reference from just
reading (first time I read it) - Maybe it could be hyphenated or similar.
Just my 2 cents

**Comment by sacdallago** [comment]
Time to :moneybag: :moneybag: :moneybag: :moneybag: :moneybag: :moneybag: 

Need final name to make blin blin

**Comment by gyachdav** [comment]
sounds like predictemall won

**Comment by sacdallago** [comment]
Namecheaping the shit out of that domain name in 10

**Comment by sacdallago** [comment]
what about predictem . today
Sounds fancy as fuck!

**Comment by AlexanderLill** [comment]
Is e.g. prectict-em-all available too? ^^

**Comment by sacdallago** [comment]
yo! but hypens in a link? So 1950s!

**Comment by goldbergtatyana** [comment]
yeah and I always read 'predict a mall' 😸

**Comment by sacdallago** [comment]
@goldbergtatyana right?!?!! Btw, can you ask inga real quick how the story of me buying it with my CC is? Like exact address I have to put aso.

**Comment by sacdallago** [comment]
Bought. Will be announced later
