### ISSUE TITLE
Improve pokedex index page

### ISSUE THREAD

**Issue by mfkaptan** [PokemonGoers/Catch-em-all#69]
Right now we only show pokemon pictures and names in the index page. Clicking a pokemon gets us to the detail page. We can improve the list in the index page, add some stats to each pokemon's card.

**Comment by WoH** [comment]
Also, we should probably go for 2 columns on mobile and 4 on desktop instead of 1 and 3, this is also part of gridlex and should not require too much additional styling if you can also take care of that.

**Comment by MajorBreakfast** [comment]
@WoH Let's have a column width and we show as many columns as we are able to fit on the screen.

About the additional info: Maybe add the Pokemon number. Anything more makes it just cluttered IMO.

**Comment by AlexanderLill** [comment]
We also wanted the pokemon rarity here, did we? Can we quickly discuss this? :)

See #86

**Comment by AlexanderLill** [comment]
We also wanted the pokemon rarity here, did we? Can we quickly discuss this? :)

@mfkaptan whats the current status here?

See #86

**Comment by AlexanderLill** [comment]
I implemented the pokemon rarity myself now: #96 

Still, what's the status here?

**Comment by AlexanderLill** [comment]
I implemented the pokemon rarity myself now: #96 

Still, what's the status here? @Lugitan @mfkaptan

**Comment by sacdallago** [comment]
@Lugitan @mfkaptan update now? Can we assume you are still alive?

**Comment by mfkaptan** [comment]
How does this look on mobile (two column view) (Discussion on gitter)

![image](https://cloud.githubusercontent.com/assets/3976573/19231300/9579f1d6-8ed9-11e6-9048-9313dcd0877d.png)

**Comment by sacdallago** [comment]
I like the idea. But a few pointers (not necessarily to be corrected, just my 2 cents):
1. I guess the number was part of the discussion, right? 5 is something most of us can relate to naturally, that's why most ordinal questionnaires span on 5 values. 3 is fine too, but at first impact most people will think "are there five or is 3 the actual maximum?".
2. Stars, in today's websites, account for popularity or how much something is liked. You are a bit forcing the viewer using the star icons, if you ask me.

I have a suggestion:
Why not use bars? As in: the bars that android uses for the signal strength of your mobile operator? These ones, to be clear:
![](https://image.freepik.com/free-icon/signal-bars_318-41832.jpg)

For these you could actually limit it to three bars, and I think it abstracts the idea better than stars. Btw: less bars, less likely to encounter

**Comment by mfkaptan** [comment]
> 1. I guess the number was part of the discussion, right? 5 is something most of us can relate to naturally, that's why most ordinal questionnaires span on 5 values. 3 is fine too, but at first impact most people will think "are there five or is 3 the actual maximum?".

I don't think people will think like that because the index page actually looks like this:
![image](https://cloud.githubusercontent.com/assets/3976573/19244540/084f5c9e-8f1d-11e6-89b1-f2ba8f497fea.png)

So IMO it is clear that 3 is maximum here.

> Stars, in today's websites, account for popularity or how much something is liked. You are a bit forcing the viewer using the star icons, if you ask me.

I'm with you on that. I'll try to change it to bars so that we can discuss further. I'm thinking something like this:

![](https://cdn3.iconfinder.com/data/icons/aami-web-internet/64/aami8-35-512.png)

**Comment by sacdallago** [comment]
@mfkaptan  I like that a lot!

**Comment by mfkaptan** [comment]
Not the final product but:

![image](https://cloud.githubusercontent.com/assets/3976573/19266621/9e38c474-8faa-11e6-93dd-a5de79e512a8.png)

@sacdallago @AlexanderLill what do you think about the bars?

**Comment by AlexanderLill** [comment]
Not bad :)

Let's discuss color ... ;)

How about some grey? Better ideas? :)

**Comment by mfkaptan** [comment]
I am using free icons from wherever I can find. I am not good at drawing or anything :( So if you can find a free icon pack for the bars with better colors ("signal strength" could be a useful keyword for searching) that would be great! I found this one from https://icons8.com/web-app/12367/medium-connection

**Comment by WoH** [comment]
I fear signal bars are confusing for as they could also indicate distance to that pokemon. Maybe a background or a badge like with a color code as shown here: [Rarity color code](http://i.imgur.com/Qmx2vF2.jpg) 

Or, for the hardcore pokemon fanatics: [GER](http://www.pokewiki.de/Seltenheit) / [ENG](http://bulbapedia.bulbagarden.net/wiki/Rarity)

**Comment by mfkaptan** [comment]
> I fear signal bars are confusing for as they could also indicate distance to that pokemon

@WoH Good point. But as a "softcore" fan I actually found those color codes confusing, for example green seems like "common" to me but it says green is for "rare" pokémons. Also I guess blue can be interpreted as a water type pokemon red as fire etc. I am not sure about the colors. I don't know if I'm the only one thinks like that. A second opinion would be good. Maybe @AlexanderLill or @sacdallago ?

Edit: https://github.com/PokemonGoers/Catch-em-all/issues/69#issuecomment-253057880

**Comment by mfkaptan** [comment]
Maybe this looks kinda ugly but how about something like this? Just think about the idea:

![image](https://cloud.githubusercontent.com/assets/3976573/19288307/c3797bb0-9005-11e6-987f-fd9d78764892.png)

**Comment by mfkaptan** [comment]
Or this:
![image](https://cloud.githubusercontent.com/assets/3976573/19289642/fc60b5f0-900b-11e6-9360-559bd6d79c39.png)

**Comment by mfkaptan** [comment]
For side-to-side comparison

![image](https://cloud.githubusercontent.com/assets/3976573/19289698/51af933c-900c-11e6-9398-c873d0939b29.png)

**Comment by mfkaptan** [comment]
Vote with thumbs up:

![image](https://cloud.githubusercontent.com/assets/3976573/19289741/78f4b4c2-900c-11e6-9b92-381d922dcfd5.png)

**Comment by mfkaptan** [comment]
~~@WoH upon request~~ Colored bars:
![image](https://cloud.githubusercontent.com/assets/3976573/19289966/861ecd3a-900d-11e6-9a41-fde5be6dbba7.png)

**Comment by WoH** [comment]
@mfkaptan I was thinking of plain old colored badges, maybe with text, do not associate my name with signal bars :cry:

**Comment by mfkaptan** [comment]
@WoH Sorry, my bad it's getting late :see_no_evil:

**Comment by mfkaptan** [comment]
@WoH Sorry, my bad it's getting late :see_no_evil: Here you go (?)

![image](https://cloud.githubusercontent.com/assets/3976573/19290689/2764a342-9011-11e6-8c0c-85820fd6c2a6.png)

**Comment by gyachdav** [comment]
Color badges make the most sense to me. Nice job @mfkaptan.

**Comment by MajorBreakfast** [comment]
Good idea. These badges are much more self-explanatory.

**Comment by mfkaptan** [comment]
Ok I guess everybody is happy with badges then. Question:

According to @WoH 's comment:

> Maybe a background or a badge like with a color code as shown here: [Rarity color code](http://i.imgur.com/Qmx2vF2.jpg) 

There are 8 color codes and rarity options from `very common` to `legendary`. Should we follow the same color coding style? same options with same colors? I think it would be nice, WDYT? @sacdallago and all?

If so, @AlexanderLill I think we should change the algorithm of rarity then, right?

**Comment by goldbergtatyana** [comment]
> There are 8 color codes and rarity options from very common to legendary. Should we follow the same color coding style? same options with same colors? I think it would be nice, WDYT?

I think +1 !

**Comment by mfkaptan** [comment]
I just found out that the rarity color chart is unofficial, and it is fan-made http://imgur.com/gallery/ZTgIu so now I am not sure about following the same style.

**Comment by gyachdav** [comment]
I'd use green to red (common to rare)

**Comment by AlexanderLill** [comment]
I agree with Guy, green orange red seems reasonable to me :)

**Comment by MajorBreakfast** [comment]
About the style: We should make a visible distinction between the rarity tags and Pokemon type tags. I propose rounded corners for one and sharp corners for the other.

**Example: Rounded corners**

![imgres](https://cloud.githubusercontent.com/assets/340142/19343056/e53620ca-9134-11e6-9f52-8c0a638f6444.png)

**Example: Sharp corners**

Imagine a rectangle :) Haha

@mfkaptan Feel free to decide which one's which. The point is that there should be a visual distinction

**Comment by mfkaptan** [comment]
Using red, orange, green and sharp corners, here is the result:

![image](https://cloud.githubusercontent.com/assets/3976573/19361661/dbe47432-9183-11e6-8057-a936e86a1c65.png)

**Comment by mfkaptan** [comment]
Which one do you think is better for the `#id` ?
![image](https://cloud.githubusercontent.com/assets/3976573/19414287/e8450d20-9347-11e6-90be-0c1b740e58d5.png) 
![image](https://cloud.githubusercontent.com/assets/3976573/19414293/44f30a68-9348-11e6-88e8-c98cf45f0e41.png)
![image](https://cloud.githubusercontent.com/assets/3976573/19414300/6e28ecae-9348-11e6-94a7-0733ab0857dc.png)
![image](https://cloud.githubusercontent.com/assets/3976573/19414304/8cc78256-9348-11e6-94f2-aeedc72e854f.png)

**Comment by goldbergtatyana** [comment]
I go for 3, as i think the id is not so important for the users. Beautiful things 👍

**Comment by sacdallago** [comment]
2 For me :see_no_evil: that slightly little different BG color in 3 makes me cry a little

**Comment by goldbergtatyana** [comment]
I noticed the bg color only after looking closely on the phone. Didn't recognize the box when was on laptop. If we make the box fly altogether, will it make you smile again @sacdallago :))

**Comment by gyachdav** [comment]
I would just remove the ID altogether (info overload). Is there a reason we're showing it?

**Comment by mfkaptan** [comment]
@gyachdav I guess we don't have a real reason to show it, I'll ask the team

**Comment by mfkaptan** [comment]
@gyachdav Official pokedex has the ids (don't exactly know why), so I guess we could also keep them(?)
http://www.pokemon.com/us/pokedex/pikachu

**Comment by MajorBreakfast** [comment]
The id should stay. It was definitely important when I was in school. Each Pokemon had an id from 1 - 151 back then.

**Comment by gyachdav** [comment]
It serves no purpose for our app, other than knowing the ID in case you'll be trading some pokemon cards 😛 . I say remove it.

**Comment by MajorBreakfast** [comment]
Okay merged.

I think all points of this issue have been implemented, right?

**Comment by mfkaptan** [comment]
https://github.com/PokemonGoers/Catch-em-all/issues/69#issuecomment-248594147

> Let's have a column width and we show as many columns as we are able to fit on the screen.

If you are content with the pokedex-index then I guess we can close this issue.

**Comment by MajorBreakfast** [comment]
We could also add a max-width
