### ISSUE TITLE
Integrate Project B: PredictPokemon

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/Catch-em-all#7]

**Comment by goldbergtatyana** [comment]
From PredictPokemon groups you will get 1) the name of a pokemon, 2) its location, 3) time point and 4) possibly a likelihood of its appearance in percentage. For now you can generate some dummy data in a file and read it from there.

**Comment by MajorBreakfast** [comment]
What form will the integration have? Will Project B provide a JSON API? Is there an issue on the details for this in the other project? Will we interact directly with the JSON API or through the map?

**Comment by johartl** [comment]
I will close this now because the integration will happen through the PokeData team.
