### ISSUE TITLE
Filter: Pokemon Tab

### ISSUE THREAD

**Issue by MajorBreakfast** [PokemonGoers/Catch-em-all#74]
![filtermock](https://cloud.githubusercontent.com/assets/340142/18711527/aeb1c5d0-800a-11e6-84c9-4ad71749b610.jpg)
- [x] Stage 1
  - List with Pokemon that are selectable
- [x] Stage 2
  - Filter function for the Pokemon list
- [ ] Stage 3
  - Combo selection buttons for All/None and types

Here's how it's going to work:
- At the bottom there is a of all 150 Pokemon. A Pokemon can either be selected or not (boolean)
- At the top is a horizontally scrolling or paged list of buttons. Each button represents a set of Pokemon. These Pokemon sets may overlap. There is a button for each Pokemon type (a Pokemon can have multiple types) and a button for all Pokemon. A button is always in one of three states: Selected, partially selected, deselected. The button state corresponds to the selection state of the Pokomon in the button's set. E.g. if the set includes a selected Pokemon and a deselected Pokemon, the button is partially selected.

**Comment by johartl** [comment]
In develop there already is a <filter-popover-tab-pokemon> component. So how should this be named?

**Comment by AlexanderLill** [comment]
@johartl You mean the file "poke-filter-pokemon-tab.component.ts"? I think that @MajorBreakfast added this as an empty template for me to use :)

**Comment by johartl** [comment]
Yes there are two empty components
- `filter-popover-tab-pokemon.ts`
- `poke-filter-pokemon-tab.component.ts`

That's why I was confused :D

**Comment by AlexanderLill** [comment]
Okay now I am confused, too :D
@MajorBreakfast @WoH @johartl 

Which one should we continue using?

**Comment by MajorBreakfast** [comment]
I'd like to namespace all components with 'poke-' in the long run. It leads to slightly longer names, however it makes sense because components aren't organized into namespaces any other way. It'd be probably better to delete both and start by modifying a copy of the time tab.

**Comment by WoH** [comment]
Isn't FilterPopover already way too long. Honestly, seeing that poke prefix hurts my eyes

**Comment by WoH** [comment]
Also, if you feel the urge to get creative, at least fix the selectors in your new and hip components and use them consistently,.
If I see someone merge something like that to develop again may god bless your poor soul.

**Comment by AlexanderLill** [comment]
I need the types for the pokemon at some point - should we ask to include a list of all (used) types in the API, or should we just include all of them hardcoded or get this data ourselves?

I just noticed after using hardcoded types that for some types there seem to be no pokemon. Maybe it would be helpful to get them over a API request, e.g. /api/getPokemonTypes or sth :)

I got the typelist from @philbu 's code

**Comment by MajorBreakfast** [comment]
I've updated the issue with a description of the working principle.

**Comment by AlexanderLill** [comment]
@MajorBreakfast my current PR #85 includes stages 1 and 2 but still has some minor issues, e.g. an UI refresh bug and is missing some fancy CSS.

I would suggest to implement stage 3 another time, especially since your working principle seems quite hard to implement for me without providing a lot of benefit right now.

@philbu I added the list of types to the ApiService, maybe you can adjust your code in the poke-type.component.ts to use this list, too - or add the colors to the list in the ApiService and I will just ignore the colors in my code :)

**Comment by MajorBreakfast** [comment]
@AlexanderLill 

You don't need to implement everything in one PR.

As for the complexity. Well, originally we had a lot more complicated ideas swirling around: Like a whitelist and blacklist mode, different filters and what not. I think the solution @johartl, @WoH and I came up with is quite elegant. I'm confident that we can build this solution. It doesn't have to be all you, though!

**Comment by AlexanderLill** [comment]
Okay, I just merged the preliminary pokemon filter.

Open issues:
- [ ] If "select all" or "select none" is clicked the list does not immediately update. It works if the same button is clicked another time, or if any item in the list is clicked.
- [x] The layout and CSS of the dialogue could use some improvements
- [x] The pokemon-list in the lower part of the dialogue only starts loading when the searchbar is focused/clicked

@PokemonGoers/catch-em-all would be great if somebody could help me with those issues / resolve this together with me :)

**Comment by WoH** [comment]
Handled by #129
