### ISSUE TITLE
Use https to serve application

### ISSUE THREAD

**Issue by WoH** [PokemonGoers/Catch-em-all#77]
A [secure context](https://w3c.github.io/webappsec-secure-contexts/) such as [HTTPS](https://developers.google.com/web/fundamentals/security/encrypt-in-transit/?hl=en) will be [required](https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only) to access use the [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation#Browser_compatibility) for our Project.

**Comment by johartl** [comment]
I suppose we can use a certificate from [Let's encrypt](https://letsencrypt.org/).

**Comment by sacdallago** [comment]
Yeah, I'll do that on production, via let's encrypt or startssl, but rather the first one

**Comment by gyachdav** [comment]
status?

**Comment by johartl** [comment]
My understanding of this was that @sacdallago is going to take care of it? Is this still correct?

**Comment by sacdallago** [comment]
Yes. We have the domain name, I just have to buy the server, get the certificates and migrate docker cloud. My agenda says this should be done until Wednesday

**Comment by johartl** [comment]
How do you want to read the certificate inside the Docker container? Mounting a volume into the container and then use an environment variable to specify the location? 
`docker run catchemall -v ~/secret:/secret -e HTTPS_CERTIFICATE=/secret/cert.pem`

**Comment by sacdallago** [comment]
Nah: I'll just connect to the VM, install `letsencrypt`, get the certificate, reverse-proxy via nginx. It's what I'm doing with http://cell.dallago.us which really is http://cellmap-devel.bb5a8828.svc.dockerapp.io:2090 (adding the certificate layer via nginx is a joke).

**Comment by johartl** [comment]
So for requests to the API we have the client sending an https request to your nginx server which proxies the request to the CatchEmAll docker container running a node server which proxies the request to the PokeData container? :D

...

![](https://i.imgflip.com/1c3kjn.jpg)

No but seriously... Sounds fine to me. Less to do on our side :)

**Comment by AlexanderLill** [comment]
@sacdallago is this me or should https://cell.dallago.us/ then actually work instead of showing `ERR_SSL_PROTOCOL_ERROR`? :D

**Comment by sacdallago** [comment]
@AlexanderLill I never shared a link containing HTTPS ;) for that website, https would just slow requests down. No need for the extra security.

**Comment by AlexanderLill** [comment]
Ah, then I misunderstood that :D My bad :)
