### ISSUE TITLE
Implement Notification for PokeMobs

### ISSUE THREAD

**Issue by AlexanderLill** [PokemonGoers/Catch-em-all#79]
See if Ionic2 supports
- Notifications (on Android and iOS)
- Running in the background (e.g. Android Service)

For these notifications a WebSocket connection will be built which is also active if the app is not currently in the foreground / used by the user.

There should also be an option to disable this feature if it consumes too much energy on the long run, and an option for the distance-radius that we get notifications for.

**Comment by WoH** [comment]
https://ionicframework.com/docs/v2/native/local-notifications/
https://github.com/katzer/cordova-plugin-local-notifications

**Comment by MajorBreakfast** [comment]
Can someone else take that one over for me? I'm pretty busy with the MobCard, then the remaining adjustments to the filter UI. I cannot handle this as well.

**Comment by WoH** [comment]
I guess this is not going to happen, but I'll try another bump!
