### ISSUE TITLE
Mob card

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/Catch-em-all#80]
Similar to the POI card where we display a Pokemon which was clicked on we need the same for a mob. Once the user clicks on a mob a bottom sheet should slide up which shows the following information.
- The tweets which caused this mob (also see #68)
- Navigate to mob button
- Optional: Show/Name the Pokemon that was named in each tweet

**Comment by AlexanderLill** [comment]
@johartl this can be closed after #87 is merged, right?

**Comment by WoH** [comment]
@AlexanderLill No, this is the Mob card, not the POI card.

**Comment by AlexanderLill** [comment]
@WoH but i saw some code in his PR that seemd to be handling the mobs :)

**Comment by johartl** [comment]
That's a different concept because for the mobs we want to display the tweets causing that mob. But I'm sure we can reuse the swipe card and just fill it with different content.

**Comment by AlexanderLill** [comment]
Okay :) I was just trying to clean up the issues a little bit :)

**Comment by gyachdav** [comment]
is this demoable?

**Comment by MajorBreakfast** [comment]
@sacdallago Why did you assign me to this? I just saw that you assigned me a few days ago and I didn't know anything about it! If I had known I wouldn't have redesigned the PokeDex! What to do now? I can build the card. But proper mob integration is a lot more work. I thought @johartl was on it

**Comment by sacdallago** [comment]
I assigned you and @Georrgi because one week ago @johartl was overloaded and I thought it'd be fair to redistribute a bit of the work :)

I thought this was only about the design, not the full integration. I seriously hope that is taken care of.

**Comment by MajorBreakfast** [comment]
I'll take care of it. Haven't heard from @Georrgi for quite a while now.

**Comment by MajorBreakfast** [comment]
I'll take care of it.

BTW I haven't heard from @Georrgi for quite a while now. He hasn't contributed to the project so far. I unassign him for now.

I will work on this this evening.

**Comment by sacdallago** [comment]
Good to know

**Comment by MajorBreakfast** [comment]
#131 implements the PokeMob card
