### ISSUE TITLE
Popover styling

### ISSUE THREAD

**Issue by WoH** [PokemonGoers/Catch-em-all#82]
Hey guys, does anyone want to take over and do the popover styling?
I experimented briefly and I think the popover should be -500px 300px width on android and I'll check iOS later but definitely different. You can do this by moving the popover class out of the global stylesheet and redefining it on a per-platform basis (style.platform.css).
Also we should discuss the text because it currently takes up a lot of space on mobild devices.

**Comment by MajorBreakfast** [comment]
I've a nice replacement for the ionic popover in the works. It will be responsive and styled nicely. https://github.com/PokemonGoers/Catch-em-all/pull/83

**Comment by WoH** [comment]
I already fixed that anyway.
