### ISSUE TITLE
Implement pokemon rarity in pokedex detail view / pokedex overview

### ISSUE THREAD

**Issue by AlexanderLill** [PokemonGoers/Catch-em-all#86]
Hello everyone,

the rarity and appearance likelihood are now available on the API after our request (https://github.com/PokemonGoers/PokeData/issues/163) has been implemented.

We should discuss where specifically and how we want to use this data now - let's collect some ideas :)

**Comment by johartl** [comment]
Two ideas
- The ranking we could show in the pokedex alongside the other Pokemon stats (e.g. CP, flee rate,..)
- In the pokedex index page where all Pokemon are shown and/or in the Pokemon filter tab we could show a star-based indication of the Pokemon rarity. For instance, Pidgey gets one star and the legendary Pokemon get three stars. This lets the user spot rare Pokemon more easily.

**Comment by WoH** [comment]
![statchart](https://cloud.githubusercontent.com/assets/2697771/18911998/64315252-8580-11e6-8fe7-3a4aca42ceeb.png)

I am working on something like this for the stats, maybe include rarity there?
Or just another chart but use stars instead of a bar?

**Comment by johartl** [comment]
I wouldn't include it in these bars. These stats are all related to the Pokemon's abilities (How strong is that Pokemon). Just because a Pokemon is rare does not make it stronger so that shouldn't affect the _Total_ value and I think we should place that information somewhere else.
Also, can you create a legend for the stats (HP, ATK, ..) somewhere. I have no idea what SPA and SPD stand for. Or maybe just use the full name?

**Comment by WoH** [comment]
Well this is standard Pokemon lingo, so idk, but changing the title isn't gonna make or break it :wink:

**Comment by AlexanderLill** [comment]
I added the fields in the model and a basic overview over the rarity to the pokedex-detail-page for now (see #91)

**Comment by AlexanderLill** [comment]
@PokemonGoers/catch-em-all did somebody start with the visualisation for the pokewiki search page yet?

Are we doing the 3-stars-approach, or do we have better ideas? Is there maybe any visualisation that is used in the PokemonGo app already?

**Comment by johartl** [comment]
I don't think the PokemonGo app has a notion of rarity build in. After all, that's probably information they don't want to disclose so easily ;) 
I like the idea of using stars but I would also be open for other suggestions.

**Comment by AlexanderLill** [comment]
See a very simple implementation of this now in the PokeDex here: #96 

I will close this issue after merging this PR.

**Comment by AlexanderLill** [comment]
PR #96 was merged.
