### ISSUE TITLE
Integrate Project D: PokeMap

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/Catch-em-all#9]

**Comment by MajorBreakfast** [comment]
What form will the integration have? Will the project be teams design some kind of client-side JavaScript API for us to use to display their map? Is there an issue for this in the other project?

**Comment by sacdallago** [comment]
CC: @PokemonGoers/pokemap-1 @PokemonGoers/pokemap-2 

the way it was done last semester, was that the map was packaged in an npm package which the web-project guys just had to download via package.json and use in their webpages (a simple `div` to stick wherever you need it).

There are though some initialization parameters that you would need to keep in mind, as: source of the data, center of the map, etc.

Additionally the map guys might need to integrate twitter API keys, so make sure that this is also part of the config when setting up the map.

You can check out web-pack or browserify, or the AMD pattern or whatever not to bundle your app.

**Comment by MajorBreakfast** [comment]
Here's a summary:

### What we (Project E) do:
- Initialize the map
  
  e.g. `new PokeMap(div, options)`
- Create the actual UI around the map: Buttons (for zooming, etc.), dialogs

### What the mapping teams (Project D) do:
- Create map itself, not the UI around
- Create a client side API, a script for us to include
  - Define which options the map expects at initialization
  - Provide methods for us that we can call when we need the map to do something, e.g. go to a specific location, zoom in/out
    
    e.g. `pokeMap.goTo({ longitude, latitude })`
  - Trigger events to which we can listen to when our UI should display something
    
    e.g. `pokeMap.on('clickedPokemon', (pokemon) => { ourUI.doSomething(pokemon) }`)
  - The map teams design the API and document it, project E uses what they provide

---

Tell me what you think. Would that work for everyone involved? Let's get some feedback from the map team members.

**Comment by AlexanderLill** [comment]
Let's see if it works when we just mention them? :D
@PokemonGoers/pokemap-1 @PokemonGoers/pokemap-2

**Comment by timobrembeck** [comment]
To me this distribution of functionality sounds very reasonable.
As this wasn't clarified in our task's description, we already implemented some parts of the UI (popups and sidebar - see [demo](https://pokemongoers.github.io/PokeMap-2/)), but we could also provide an API as described above.

A disadvantage for us would be that we partially worked for nothing - except you can use our UI-parts.

**Comment by MajorBreakfast** [comment]
@timoludwig Nice. Plz keep us in the loop about how the API will look like

**Comment by gyachdav** [comment]
@timoludwig not sure what UI you worked on for nothing. Currently all UI features I see (map rendering, zoom buttons, popups) are integral part of your app. 

The project that is most likely to make use of your app, project E,  needs to think how to best integrate your app into their web app:
- Initialize the map
- Listen to events that happen in the map 
- modify the state of the map as needed 

I do not see zooming as part of the web app job (you wouldn't expect them to implement the navigation buttons either, would you?) nor the popups. 

At any rate, keep coordinating this with your primary customer project E and make sure to document your application level functionality i.e. what your params and functionality you expose to callers and what events you bubble.

**Comment by timobrembeck** [comment]
@gyachdav thanks for the explanation. There's also a sidebar (opens when clicking on the book-icon), but as you say we could keep that as part of our app.

@PokemonGoers/catch-em-all what do you think about filtering the map by a certain time range: do we just provide the methods or also the UI?

**Comment by gyachdav** [comment]
I don't see any side bar on safari 9.1.1 and chrome. Haven't tried on ios though. 
![screen shot 2016-08-31 at 11 18 13 pm](https://cloud.githubusercontent.com/assets/4074881/18144871/7d272602-6fd1-11e6-9786-5fdb9ac69473.png)

**Comment by gyachdav** [comment]
found it, ignore my prev comment 😆

**Comment by johartl** [comment]
I created a skeleton of how to integrate the map(s) into our project. The interface is in accordance to #24 but some methods are still missing. Unfortunately, the app crashes when starting due to different errors in the respective PokeMap projects.
I will continue to work on this in the next few days. Until then please check out the branch `pokemap` and feel free to contribute :)

**Comment by sacdallago** [comment]
This can be closed, I believe.

Although: what is the 

``` javascript
core.710ed51….bundle.js:2234 GET http://localhost:3000/socket.io/EIO=3&transport=polling&t=LUJQPhH net::ERR_CONNECTION_REFUSED
```

error?

Then:
- Will the center and zoom be automatically adjusted to the user's location when on https?
- Can you set a closer zoom level for the default + set the center at some location. It's always nice to have a fallback, which might as well be TUM or a funny address, eg. `48.132100, 11.546914`  :laughing:

**Comment by johartl** [comment]
The `HTTP GET` error is arises because one of the pokemap teams is expecting the websockets to be available at `localhost:3000`. This should be fixed by https://github.com/PokemonGoers/PokeData/issues/168.

> Will the center and zoom be automatically adjusted to the user's location when on https?

Yes it should. It already does when running locally.

> Can you set a closer zoom level for the default + set the center at some location. It's always nice to have a fallback, which might as well be TUM or a funny address, eg. 48.132100, 11.546914  :laughing:

This is done by the PokeMap team. We told them to initialize the map "somehow". You would need to address this issue to them.

I will close this now.

**Comment by sacdallago** [comment]
Thanks @johartl :)

**Comment by sacdallago** [comment]
@PokemonGoers/pokemap-1 could you please also take care of this, @timoludwig has already implemented it :)

**Comment by oleks-fedotov** [comment]
@sacdallago yes, sure. thanks for activity.
