### ISSUE TITLE
migrate to Ionic RC1

### ISSUE THREAD

**Issue by WoH** [PokemonGoers/Catch-em-all#90]
- [x] Migrate to NgModule
- [x] Base on Angular 2.0.0 Final
- [x] Update to Angular 2.1.0
- [x] ionic2-rc0 && ionic2-rc1
- [x] Switch to Rollup
- [x] New button behavior
- [x] Update CSS Link Tags
- [x] Migrate to TS 2.0
- [x] use new typings system 
- [x] new buttons, icon buttons
- [x] color attributes instead of directives
- [x] Switch to the new Lifecycle Hooks **WIP** 

> Lifecycle Events Renamed
> Renamed ionViewLoaded to ionViewDidLoad
> Removed ionViewDidUnload
> Removed fireOtherLifecycles from ViewController
- [x] Scope CSS 

> Add selectors to each of your components that are used as pages. These selectors will be used for scoped sass. With this change this is now the proper way to scope your sass for an individual page.

**Issues**:
- [x] Fix Pokemap import
- [x] Fix ionic serve
- [x] ionic browser build(local works, travis fails)
- [x] ionic android build (local works, travis fails)
- [x] Get environment variables for use in ConfigService
- [x] Fix evolutions-component
- [x] ConfigService: Proxy through /api
- [x] Rollup-Replace: Set env properly

**Additional (not MVP):**
- [x] Ahead of Time Compiling
- [x] ServiceWorker

**Abandoned:**
- Webpack - Slow and no tree-shaking. 
- Karma / Jasine
- Testing
- Properly declare modules

**Not Part of the PR:**
- Consider [Yarn](https://yarnpkg.com/)
- [Coderlyzer](https://github.com/mgechev/codelyzer)

[Laugh at my progress here](https://github.com/PokemonGoers/Catch-em-all/tree/r1)

**Comment by johartl** [comment]
Have you tried running the Docker build? For me, the cordova.js file was missing. I don't know who is supposed to generate it but apparently `ionic build browser` doesn't do the trick.

**Comment by WoH** [comment]
I'll have to look into the docker build, ionic build browser is working as intended and everything required ends up in platforms/browser/www

Edit: Using the new directory now

**Comment by WoH** [comment]
@johartl Can you look into the API Endpoint stuff (ConfigService)? I worked around that to make it work locally, maybe you can reintroduce the env variables?

**Comment by johartl** [comment]
Environment variables are fixed. Docker should also work. 
Please avoid relying on any globally installed packages (e.g. `npm install -g cordova`) and install them locally instead. I also removed the `rm -rf node_modules` line you've introduced. This is just gonna give us painfully long Travis builds. If there should be any issues with npm installs you can always just clear the cache.

**Comment by WoH** [comment]
I had to do it one time to solve an issue with npm. However, keeping it is not neccessairy, I agree. Same thing goes for the cordova. previously, the builds were failing because n_m/.bin/ionic build would try to get plugins using cordova.

**Comment by gyachdav** [comment]
when is the MVP out?

**Comment by WoH** [comment]
This will be merged after the beta probably.
It is in a solid state but we have to take care of enough things so we don't want to add additional complexity for now, since the migration involves a completely new build process and breaking changes in both Ionic and Angular

**Comment by WoH** [comment]
Updated

**Comment by MajorBreakfast** [comment]
@sacdallago This issue requires a lot of experience with ionic 2. Should @Georrgi still want to contribute we could find something easier for him. I'm unassigning him here since @WoH has it covered (See rc1 branch). I hope that's okay.

**Comment by WoH** [comment]
I didn't even see this until now, I agree. Me and @johartl are/will be doing fine here.

**Comment by WoH** [comment]
Updated.
