### ISSUE TITLE
Persist filter options in local storage

### ISSUE THREAD

**Issue by WoH** [PokemonGoers/Catch-em-all#97]
Implement a FilterService that sets the filter when the app is starting up and persists the settings in the local storage.

Would be a good contribution for someone who is looking to contribute @PokemonGoers/catch-em-all

**Comment by johartl** [comment]
I'm working on this.

**Comment by WoH** [comment]
See https://github.com/PokemonGoers/Catch-em-all/issues/101#issuecomment-252490998
